'use strict';

/*
 * Banco do modo Veni, Vidi, Vici: uma palavra e tres dicas.
 *
 * As dicas sao **soltas, nao frases**: cada uma e um nome, um lugar ou um
 * detalhe que so faz sentido junto com os outros dois. "Michael Jackson",
 * "Mike Tyson" e "Taffarel" levam a `Luva`; "Kill Bill", "taxi de Nova York"
 * e "Pikachu" levam a `Amarelo`. A graca esta em achar o que liga as tres.
 *
 * Regras para escrever uma entrada nova:
 *
 * - **A dica nunca contem a resposta**, nem em outra forma ("formigueiro"
 *   entrega `Formiga`). `testes/veni.test.js` reprova a que escorregar.
 * - **Tres dicas**, da mais enviesada para a mais direta. Se a primeira ja
 *   entrega sozinha, ela esta no lugar errado.
 * - **Curta**: duas ou tres palavras. Definicao de dicionario estraga o jogo.
 * - **Seca**: so a referencia, sem a explicacao do vinculo junto. "Cicatriz de
 *   Harry Potter" ja diz onde esta o `Raio`; "Harry Potter" deixa a pessoa
 *   achar sozinha. Assim tambem "marcha de Gandhi" -> "Gandhi", "passar roupa"
 *   -> "Passar", "sapo virando principe" -> "Sapo". Titulo inteiro nao e
 *   explicacao: "O Lobo de Wall Street" fica como esta.
 * - **Duas cartas nao abrem com a mesma primeira dica**: na janela de 15s e so
 *   ela que esta na tela, e o palpite e um por pessoa. Repetir a referencia da
 *   segunda dica em diante vale — a Ferrari abre `Vermelho` e fecha `Cavalo`.
 * - **Sem acento**, como no resto do texto do jogo.
 * - `aceita` guarda as outras grafias que valem — a comparacao ja perdoa
 *   acento, maiuscula e pontuacao sozinha.
 */

const PALAVRAS = [
  { resposta: 'Cavalo', dicas: ['Presente de Troia', 'Ferrari', 'Pula em L no xadrez'], dif: 25 },
  { resposta: 'Amarelo', dicas: ['Kill Bill', 'Taxi', 'Pikachu'], dif: 30 },
  { resposta: 'Luva', dicas: ['Michael Jackson', 'Mike Tyson', 'Taffarel'], dif: 35 },
  { resposta: 'Vermelho', dicas: ['Ferrari', 'Joseph Stalin', 'Chapolin'], dif: 25 },
  { resposta: 'Lua', dicas: ['Neil Armstrong', 'Lobisomem', 'Mare alta'], dif: 20 },
  { resposta: 'Sol', dicas: ['Icaro', 'Girassol', 'Eclipse'], dif: 20 },
  { resposta: 'Espelho', dicas: ['Madrasta', 'Narciso', 'Sete anos de azar'], dif: 30 },
  { resposta: 'Maca', dicas: ['Isaac Newton', 'Guilherme Tell', 'Apple'], aceita: ['Maçã'], dif: 25 },
  { resposta: 'Coroa', dicas: ['Rolex', 'Burger King', 'Miss Universo'], dif: 30 },
  { resposta: 'Ouro', dicas: ['Rei Midas', 'Bau de pirata', 'Primeiro lugar'], dif: 20 },
  { resposta: 'Guarda-chuva', dicas: ['Mary Poppins', 'Rihanna', 'Pinguim do Batman'], aceita: ['Guarda chuva', 'Sombrinha'], dif: 30 },
  { resposta: 'Chuva', dicas: ['Gene Kelly', 'Arca de Noe', 'Nuvem carregada'], dif: 20 },
  { resposta: 'Relogio', dicas: ['Coelho de Alice', 'Dali derretendo', 'Suica'], dif: 25 },
  { resposta: 'Coracao', dicas: ['Homem de Lata', 'Emoji vermelho', 'Batida no peito'], dif: 20 },
  { resposta: 'Sombra', dicas: ['Peter Pan', 'Sol a pino', 'Silhueta no chao'], dif: 35 },
  { resposta: 'Dente', dicas: ['Fada do travesseiro', 'Dracula', 'Broca do dentista'], dif: 25 },
  { resposta: 'Osso', dicas: ['Cachorro no quintal', 'Bandeira pirata', 'Raio-x'], dif: 25 },
  { resposta: 'Sino', dicas: ['Quasimodo', 'Treno do Papai Noel', 'Torre da igreja'], dif: 30 },
  { resposta: 'Escada', dicas: ['Led Zeppelin', 'Azar de passar embaixo', 'Degrau e corrimao'], dif: 35 },
  { resposta: 'Ponte', dicas: ['Golden Gate', 'Trol dos contos', 'Rio-Niteroi'], dif: 25 },
  { resposta: 'Bicicleta', dicas: ['E.T. voando', 'Tour de France', 'Pedal e guidao'], dif: 20 },
  { resposta: 'Piano', dicas: ['Tom Hanks', 'Schroeder do Snoopy', '88 teclas'], dif: 30 },
  { resposta: 'Guitarra', dicas: ['Jimi Hendrix', 'Fender', 'Seis cordas'], dif: 25 },
  { resposta: 'Coringa', dicas: ['Heath Ledger', 'Baralho', 'Gotham'], aceita: ['Curinga', 'Joker'], dif: 25 },
  { resposta: 'Aranha', dicas: ['Peter Parker', 'Teia no canto', 'Oito patas'], dif: 20 },
  { resposta: 'Abelha', dicas: ['Maya', 'Mel', 'Ferrao'], dif: 20 },
  { resposta: 'Elefante', dicas: ['Dumbo', 'Anibal', 'Tromba'], dif: 20 },
  { resposta: 'Tubarao', dicas: ['Spielberg em 1975', 'Barbatana na agua', 'Fileiras de dente'], dif: 25 },
  { resposta: 'Pinguim', dicas: ['Madagascar', 'Antartida', 'Parece de smoking'], dif: 20 },
  { resposta: 'Formiga', dicas: ['A cigarra da fabula', 'Fila indiana', 'Carrega folha'], dif: 20 },
  { resposta: 'Borboleta', dicas: ['Efeito do caos', 'Casulo', 'Nado olimpico'], dif: 30 },
  { resposta: 'Camelo', dicas: ['Saara', 'Corcova', 'Beduino'], dif: 25 },
  { resposta: 'Coruja', dicas: ['Hedwig', 'Cabeca que gira', 'Caca de noite'], dif: 20 },
  { resposta: 'Lobo', dicas: ['Tres porquinhos', 'Romulo e Remo', 'Uivo em bando'], dif: 25 },
  { resposta: 'Leao', dicas: ['Zodiaco', 'Simba', 'As Cronicas de Narnia'], dif: 15 },
  { resposta: 'Cobra', dicas: ['Eva no paraiso', 'Simbolo da farmacia', 'Troca de pele'], dif: 20 },
  { resposta: 'Rato', dicas: ['Ratatouille', 'Mickey', 'Queijo na armadilha'], dif: 25 },
  { resposta: 'Pizza', dicas: ['Napoles', 'Tartarugas Ninja', 'Oito fatias'], dif: 15 },
  { resposta: 'Chocolate', dicas: ['Willy Wonka', 'Cacau', 'Ovo de Pascoa'], dif: 15 },
  { resposta: 'Cafe', dicas: ['Starbucks', 'Porto de Santos', 'Expresso'], dif: 20 },
  { resposta: 'Queijo', dicas: ['Tom e Jerry', 'Buraco no desenho', 'Minas'], dif: 20 },
  { resposta: 'Banana', dicas: ['Velvet Underground', 'Minions', 'Casca escorregadia'], dif: 20 },
  { resposta: 'Batata', dicas: ['Perdido em Marte', 'McDonalds', 'Pure'], dif: 25 },
  { resposta: 'Ovo', dicas: ['Humpty Dumpty', 'Veio antes da galinha', 'Gema e clara'], dif: 15 },
  { resposta: 'Gelo', dicas: ['Zero grau', 'Elsa', 'Titanic'], dif: 15 },
  { resposta: 'Fogo', dicas: ['Inferno', 'Joana d\'Arc', 'Motoqueiro Fantasma'], dif: 20 },
  { resposta: 'Vento', dicas: ['Dom Quixote', 'Furacao', 'Vela do barco'], dif: 30 },
  { resposta: 'Deserto', dicas: ['Pequeno Principe', 'Duna', 'Miragem'], dif: 25 },
  { resposta: 'Ilha', dicas: ['Robinson Crusoe', 'Napoleao', 'Cercada de agua'], dif: 25 },
  { resposta: 'Farol', dicas: ['Navio na costa', 'Torre listrada', 'Alto do carro'], dif: 35 },
  { resposta: 'Navio', dicas: ['Proa e ancora', 'Moby Dick', 'Cruzeiro de ferias'], dif: 20 },
  { resposta: 'Foguete', dicas: ['Apollo 11', 'SpaceX', 'Contagem regressiva'], dif: 25 },
  { resposta: 'Bussola', dicas: ['Jack Sparrow', 'Rosa dos ventos', 'Agulha no norte'], dif: 35 },
  { resposta: 'Mapa', dicas: ['X do tesouro', 'Dora', 'Escala e legenda'], dif: 25 },
  { resposta: 'Livro', dicas: ['Gutenberg', 'Biblioteca de Alexandria', 'Capa e pagina'], dif: 15 },
  { resposta: 'Telefone', dicas: ['Graham Bell', 'Disco de girar', 'Alguem ligando'], dif: 15 },
  { resposta: 'Camera', dicas: ['Kodak', 'Paparazzo', 'Lente e flash'], dif: 25 },
  { resposta: 'Espada', dicas: ['Dom Pedro I', 'Rei Arthur', 'He-Man'], dif: 25 },
  { resposta: 'Escudo', dicas: ['Capitao America', 'Perseu', 'Camisa do time'], dif: 30 },
  { resposta: 'Anel', dicas: ['Frodo', 'NBA', 'Dedo do casamento'], dif: 25 },
  { resposta: 'Chapeu', dicas: ['Seletora de Hogwarts', 'Indiana Jones', 'Coelho do magico'], dif: 30 },
  { resposta: 'Palhaco', dicas: ['O filme de 2017', 'Nariz vermelho', 'Picadeiro'], dif: 20 },
  { resposta: 'Circo', dicas: ['Cirque du Soleil', 'Lona listrada', 'Trapezio'], dif: 25 },
  { resposta: 'Cinema', dicas: ['Oscar', 'Irmaos Lumiere', 'Pipoca no escuro'], dif: 15 },
  { resposta: 'Carnaval', dicas: ['Sapucai', 'Rei Momo', 'Trio eletrico'], dif: 20 },
  { resposta: 'Natal', dicas: ['Jesus Cristo', 'Charles Dickens', 'Esqueceram de Mim'], dif: 20 },
  { resposta: 'Sonho', dicas: ['Martin Luther King', 'Freddy Krueger', 'A Bela Adormecida'], dif: 30 },
  { resposta: 'Tempo', dicas: ['Dark', 'O Exterminador do Futuro', 'A Hora do Brasil'], dif: 35 },
  { resposta: 'Silencio', dicas: ['Simon e Garfunkel', 'Um minuto em homenagem', 'Regra da biblioteca'], dif: 40 },
  { resposta: 'Dinheiro', dicas: ['Quebrando a Banca', '50 Cent', 'O Lobo de Wall Street'], dif: 20 },
  { resposta: 'Diamante', dicas: ['Lucy in the Sky', 'Mais duro da natureza', 'Anel de noivado'], dif: 30 },
  { resposta: 'Bola', dicas: ['Wilson', '32 gomos', 'Quica e rola'], dif: 20 },
  { resposta: 'Dado', dicas: ['A sorte esta lancada', 'Banco Imobiliario', 'Seis faces'], dif: 35 },
  { resposta: 'Carta', dicas: ['Carteiro', 'Truco', 'Selo e envelope'], dif: 30 },
  { resposta: 'Estrela', dicas: ['Bandeira dos Estados Unidos', 'Reis Magos', 'Cinco pontas'], dif: 25 },
  { resposta: 'Arco-iris', dicas: ['Pote de ouro', 'Over the Rainbow', 'Sete cores'], aceita: ['Arco iris'], dif: 25 },
  { resposta: 'Cerebro', dicas: ['Pinky', 'Vinte por cento da energia', 'Dentro do cranio'], dif: 30 },
  { resposta: 'Sangue', dicas: ['Dracula', 'Tipo O negativo', 'Corre na veia'], dif: 25 },
  { resposta: 'Agua', dicas: ['Moises abrindo o mar', 'H2O', 'Ferve a 100 graus'], dif: 15 },
  { resposta: 'Areia', dicas: ['Ampulheta', 'Vidro derretido', 'Praia e deserto'], dif: 30 },
  { resposta: 'Vulcao', dicas: ['Pompeia', 'Montanha da Perdicao', 'Lava e cratera'], dif: 25 },
  { resposta: 'Montanha', dicas: ['Everest', 'Sisifo', 'Pico nevado'], dif: 20 },
  { resposta: 'Floresta', dicas: ['Chapeuzinho Vermelho', 'Arvore sem fim', 'Onca e tucano'], aceita: ['Selva', 'Mata'], dif: 20 },
  { resposta: 'Neve', dicas: ['Boneco de cenoura', 'Floco unico', 'Inverno branco'], dif: 20 },
  { resposta: 'Praia', dicas: ['Copacabana', 'Guarda-sol', 'Areia e mar'], dif: 15 },
  { resposta: 'Xadrez', dicas: ['Kasparov', 'Xeque-mate', '64 casas'], dif: 25 },
  { resposta: 'Futebol', dicas: ['Copa do Mundo', 'Pele', 'Onze de cada lado'], dif: 10 },
  { resposta: 'Boxe', dicas: ['Rocky Balboa', 'Muhammad Ali', 'Ringue e gongo'], dif: 20 },
  { resposta: 'Oculos', dicas: ['Harry Potter', 'John Lennon', 'Lente e armacao'], dif: 20 },
  { resposta: 'Sapato', dicas: ['Cinderela', 'Dorothy batendo tres vezes', 'Cadarco e sola'], dif: 20 },
  { resposta: 'Cadeira', dicas: ['Jogo da danca', 'Nome do diretor atras', 'Quatro pes e encosto'], dif: 25 },
  { resposta: 'Chave', dicas: ['Ben Franklin', 'Fundo da bolsa', 'Fechadura'], dif: 25 },
  { resposta: 'Janela', dicas: ['Microsoft', 'Gato olhando a rua', 'Vidro e cortina'], dif: 30 },
  { resposta: 'Cama', dicas: ['Bicho-papao embaixo', 'John e Yoko', 'Colchao e travesseiro'], dif: 25 },
  { resposta: 'Porta', dicas: ['Monstros S.A.', 'Olho magico', 'Macaneta'], dif: 25 },
  { resposta: 'Leite', dicas: ['Pires do gato', 'Vaca', 'Vira queijo'], dif: 15 },
  { resposta: 'Fantasma', dicas: ['Ghostbusters', 'Pac-Man', 'Lencol branco'], dif: 25 },
  { resposta: 'Zumbi', dicas: ['Thriller', 'The Walking Dead', 'Anda atras de cerebro'], dif: 25 },
  { resposta: 'Robo', dicas: ['Isaac Asimov', 'Arnold Schwarzenegger', 'Wall-E'], aceita: ['Robô'], dif: 25 },
  { resposta: 'Ovelha', dicas: ['Contar para dormir', 'Dolly clonada', 'La e be'], dif: 25 },
  { resposta: 'Barba', dicas: ['Papai Noel', 'Hipster', 'Navalha do barbeiro'], dif: 30 },
  { resposta: 'Sereia', dicas: ['Ariel', 'Odisseu amarrado ao mastro', 'Meia mulher, meio peixe'], dif: 25 },
  { resposta: 'Trovao', dicas: ['Thor', 'Vem depois do relampago', 'Barulho da tempestade'], dif: 30 },
  { resposta: 'Ponte aerea', dicas: ['Rio e Sao Paulo', 'Congonhas e Santos Dumont', 'Voo de uma hora'], aceita: ['Ponte-aerea'], dif: 45 },
  { resposta: 'Gol', dicas: ['Maracana em 1950', 'Volkswagen', 'Rede balancando'], dif: 30 },
  { resposta: 'Coqueiro', dicas: ['Ilha de desenho animado', 'Agua de coco', 'Arvore da praia'], dif: 35 },

  /* Tres coisas que so se encontram na mesma palavra: aeroporto, boate e
     Formula 1 tem pista; impressora, caneta e pintor tem tinta. */
  { resposta: 'Tinta', dicas: ['Impressora', 'Caneta', 'Pintor'], dif: 35 },
  { resposta: 'Pista', dicas: ['Aeroporto', 'Boate', 'Formula 1'], dif: 40 },
  { resposta: 'Galo', dicas: ['Cresce na cabeca', 'Canta cedo', 'Atletico Mineiro'], dif: 35 },
  { resposta: 'Bateria', dicas: ['Celular', 'Escola de samba', 'Carro que nao liga'], dif: 35 },
  { resposta: 'Linha', dicas: ['Agulha', 'Onibus da cidade', 'Telefone ocupado'], dif: 40 },
  { resposta: 'Ponto', dicas: ['Fim da frase', 'Onibus esperando', 'Bordado'], dif: 40 },
  { resposta: 'Banco', dicas: ['Praca da cidade', 'Reservas do time', 'Fila do caixa'], dif: 35 },
  { resposta: 'Caixa', dicas: ['Papelao fechado', 'Fila do supermercado', 'Instrumento de percussao'], dif: 40 },
  { resposta: 'Cabo', dicas: ['Panela', 'Exercito', 'HDMI'], dif: 45 },
  { resposta: 'Manga', dicas: ['Camisa', 'Quadrinho japones', 'Fruta do verao'], dif: 35 },
  { resposta: 'Pena', dicas: ['Passaro', 'Sentenca do juiz', 'Escrever com tinteiro'], dif: 40 },
  { resposta: 'Vela', dicas: ['Bolo de aniversario', 'Barco sem motor', 'Apagao em casa'], dif: 35 },
  { resposta: 'Cola', dicas: ['Prova escondida', 'Papelaria', 'Refrigerante preto'], dif: 40 },
  { resposta: 'Serra', dicas: ['Madeireiro', 'Petropolis', 'Cordilheira'], dif: 45 },
  { resposta: 'Folha', dicas: ['Outono', 'Caderno', 'Jornal paulista'], dif: 35 },
  { resposta: 'Raiz', dicas: ['Arvore', 'Dente', 'Matematica'], dif: 40 },
  { resposta: 'Copa', dicas: ['Mundial de futebol', 'Alto da arvore', 'Comodo ao lado da cozinha'], dif: 40 },
  { resposta: 'Nota', dicas: ['Partitura', 'Boletim', 'Carteira'], dif: 40 },
  { resposta: 'Tela', dicas: ['Pintor', 'Cinema', 'Celular'], dif: 35 },
  { resposta: 'Peca', dicas: ['Teatro', 'Xadrez', 'Mecanico'], aceita: ['Peça'], dif: 40 },
  { resposta: 'Prato', dicas: ['Percussao', 'Balanca', 'Almoco'], dif: 40 },
  { resposta: 'Grade', dicas: ['Prisao', 'Horario da escola', 'Janela protegida'], dif: 45 },
  { resposta: 'Corrente', dicas: ['Bicicleta', 'Rio puxando', 'Pescoco de ouro'], dif: 40 },
  { resposta: 'Onda', dicas: ['Surfista', 'Radio antigo', 'Torcida no estadio'], dif: 35 },
  { resposta: 'Pilha', dicas: ['Controle remoto', 'Monte de roupa', 'Nervoso demais'], dif: 40 },
  { resposta: 'Bomba', dicas: ['Hiroshima', 'Posto de gasolina', 'Reprovar na prova'], dif: 40 },
  { resposta: 'Bala', dicas: ['Revolver', 'Halloween', 'Papel torcido'], dif: 35 },
  { resposta: 'Capa', dicas: ['Super-heroi', 'Revista de banca', 'Dia de chuva'], dif: 35 },
  { resposta: 'Papel', dicas: ['Origami', 'Ator no filme', 'Banheiro'], dif: 35 },
  { resposta: 'Mala', dicas: ['Pessoa chata', 'Rodinhas', 'Aeroporto'], dif: 35 },
  { resposta: 'Gato', dicas: ['Ligacao clandestina', 'Sete vidas', 'Cai sempre de pe'], dif: 30 },
  { resposta: 'Zebra', dicas: ['Resultado inesperado', 'Faixa de pedestre', 'Savana africana'], dif: 35 },
  { resposta: 'Cauda', dicas: ['Piano de concerto', 'Cometa', 'Vestido de noiva'], dif: 40 },
  { resposta: 'Asas', dicas: ['Pegaso', 'Aerosmith', 'Constantine'], aceita: ['Asa'], dif: 35 },
  { resposta: 'Lente', dicas: ['Oculos de grau', 'Fotografo', 'Telescopio'], dif: 30 },
  { resposta: 'Rede', dicas: ['Pescador', 'Varanda do Nordeste', 'Atras do goleiro'], dif: 35 },
  { resposta: 'Flecha', dicas: ['Cupido', 'Robin Hood', 'Arco e alvo'], dif: 25 },
  { resposta: 'Balanca', dicas: ['Justica', 'Signo de outubro', 'Acougue'], aceita: ['Balança'], dif: 30 },
  { resposta: 'Trono', dicas: ['Game of Thrones', 'Sala do rei', 'Apelido do vaso'], dif: 35 },
  { resposta: 'Espuma', dicas: ['Chopp', 'Barbear', 'Mar batendo'], dif: 35 },
  { resposta: 'Bolha', dicas: ['Sabao', 'Chiclete', 'Sapato apertado'], dif: 30 },
  { resposta: 'Pedra', dicas: ['Rolling Stones', 'Davi contra Golias', 'Rim doendo'], dif: 35 },
  { resposta: 'Fita', dicas: ['VHS', 'Cabelo de crianca', 'Isolante'], dif: 35 },
  { resposta: 'Bolo', dicas: ['Vela e parabens', 'Nao apareceu no encontro', 'Forno'], dif: 30 },
  { resposta: 'Rolha', dicas: ['Vinho', 'Cortica', 'Abre com barulho'], dif: 30 },
  { resposta: 'Casca', dicas: ['Banana no chao', 'Ovo quebrado', 'Tronco da arvore'], dif: 30 },
  { resposta: 'Garfo', dicas: ['Xadrez', 'Macarrao', 'Tridente'], dif: 35 },
  { resposta: 'Mesa', dicas: ['Cavaleiros de Artur', 'Bilhar', 'Almoco de domingo'], dif: 30 },
  { resposta: 'Vinho', dicas: ['Uva pisada', 'Missa', 'Taca de cristal'], dif: 25 },
  { resposta: 'Chifre', dicas: ['Touro', 'Viking', 'Rinoceronte'], dif: 30 },
  { resposta: 'Cadeado', dicas: ['Ponte de Paris', 'Bicicleta na rua', 'Segredo de tres numeros'], dif: 30 },
  { resposta: 'Sirene', dicas: ['Ambulancia', 'Policia', 'Fim do expediente'], dif: 30 },
  { resposta: 'Bigode', dicas: ['Chaplin', 'Mario do Nintendo', 'Freddie Mercury'], dif: 30 },

  /* Cartas do baralho de palavra-chave: tres referencias de campos diferentes
     (um filme, um personagem historico, um livro) que so se cruzam na palavra. */
  { resposta: 'Musico', dicas: ['O Pianista', 'Mozart', 'O Violinista no Telhado'], dif: 30 },
  { resposta: 'Pes', dicas: ['Tio Patinhas', 'Aquiles', 'O Hobbit'], aceita: ['Pe'], dif: 40 },
  { resposta: 'Hotel', dicas: ['O Iluminado', 'Paris Hilton', 'Psicose'], dif: 35 },
  { resposta: 'Olhos', dicas: ['Mike Wazowski', 'Ciclope', 'O Senhor dos Aneis'], aceita: ['Olho'], dif: 35 },
  { resposta: 'Amigos', dicas: ['Toy Story', 'Jennifer Aniston', 'Como Eu Conheci Sua Mae'], aceita: ['Amigo', 'Amizade'], dif: 40 },
  { resposta: 'Trem', dicas: ['Minas Gerais', 'Barao de Maua', 'Central do Brasil'], dif: 40 },
  { resposta: 'Mao', dicas: ['Diego Maradona', 'Jaime Lannister', 'Capitao Gancho'], dif: 35 },
  { resposta: 'Selva', dicas: ['Amazonia', 'Mogli', 'O Predador'], aceita: ['Floresta'], dif: 35 },
  { resposta: 'Pintor', dicas: ['Andy Warhol', 'Michelangelo', 'Frida'], aceita: ['Pintora'], dif: 30 },
  { resposta: 'Aviao', dicas: ['Apertem os cintos', 'Santos Dumont', 'Top Gun'], dif: 30 },
  { resposta: 'Peixe', dicas: ['Tubarao', 'Aquaman', 'Procurando Nemo'], dif: 25 },
  { resposta: 'Drogas', dicas: ['Euphoria', 'Jim Morrison', 'Narcos'], aceita: ['Droga'], dif: 35 },
  { resposta: 'Cego', dicas: ['Stevie Wonder', 'Jose Saramago', 'Demolidor'], aceita: ['Cegueira'], dif: 35 },
  { resposta: 'Espiao', dicas: ['Missao Impossivel', 'Austin Powers', 'Licenca para Matar'], aceita: ['Espionagem'], dif: 30 },
  { resposta: 'Lenda', dicas: ['Sandy e Junior', 'Will Smith', 'Slender Man'], dif: 45 },
  { resposta: 'Mafia', dicas: ['Martin Scorsese', 'Al Capone', 'Familia Soprano'], dif: 30 },

  /* Mais cartas no mesmo molde. */
  { resposta: 'Vinganca', dicas: ['Conde de Monte Cristo', 'Hamlet', 'John Wick'], aceita: ['Vingança'], dif: 40 },
  { resposta: 'Traicao', dicas: ['Judas', 'Brutus', 'Cavalo de madeira'], aceita: ['Traição'], dif: 35 },
  { resposta: 'Gemeos', dicas: ['Romulo e Remo', 'Signo de junho', 'Fred e George Weasley'], aceita: ['Gêmeos', 'Gemeo'], dif: 35 },
  { resposta: 'Tempestade', dicas: ['Shakespeare', 'X-Men', 'Mar bravo'], dif: 40 },
  { resposta: 'Prisao', dicas: ['Alcatraz', 'Um Sonho de Liberdade', 'Prison Break'], aceita: ['Prisão', 'Cadeia'], dif: 30 },
  { resposta: 'Vampiro', dicas: ['Transilvania', 'Crepusculo', 'Robert Pattinson'], dif: 25 },
  { resposta: 'Corrida', dicas: ['Ben-Hur', 'Sao Silvestre', 'Lebre e tartaruga'], dif: 35 },
  { resposta: 'Guerra', dicas: ['Sun Tzu', 'Tolstoi', 'Normandia'], dif: 35 },
  { resposta: 'Pirata', dicas: ['Barba Negra', 'Perna de pau', 'Jack Sparrow'], dif: 25 },
  { resposta: 'Detetive', dicas: ['Scooby-Doo', 'Sherlock Holmes', 'CSI'], dif: 30 },
  { resposta: 'Medico', dicas: ['Dr. House', 'Grey\'s Anatomy', 'Hipocrates'], aceita: ['Médico'], dif: 30 },
  { resposta: 'Professor', dicas: ['Dumbledore', 'Sociedade dos Poetas Mortos', 'Charles Xavier'], dif: 35 },
  { resposta: 'Cozinheiro', dicas: ['Chapeu branco alto', 'Ratatouille', 'Gordon Ramsay'], aceita: ['Chef', 'Cozinheira'], dif: 35 },
  { resposta: 'Loucura', dicas: ['Um Estranho no Ninho', 'Camisa de forca', 'Chapeleiro Maluco'], dif: 40 },
  { resposta: 'Fome', dicas: ['Os 4 Cavaleiros do Apocalipse', 'Chaves', 'O Poco'], dif: 35 },
  { resposta: 'Mumia', dicas: ['Egito', 'Brendan Fraser', 'Sarcofago'], aceita: ['Múmia'], dif: 30 },
  { resposta: 'Farao', dicas: ['Tutancamon', 'Piramides', 'Cleopatra'], aceita: ['Faraó'], dif: 30 },
  { resposta: 'Gladiador', dicas: ['Coliseu', 'Russell Crowe', 'Espartaco'], dif: 30 },
  { resposta: 'Samba', dicas: ['Marques de Sapucai', 'Cartola', 'Fevereiro no Rio'], dif: 30 },
  { resposta: 'Dinossauro', dicas: ['Jurassic Park', 'Meteoro', 'Fossil no museu'], dif: 25 },
  { resposta: 'Mentira', dicas: ['Pinoquio', 'Poligrafo', 'Dedos cruzados'], dif: 35 },
  { resposta: 'Tesouro', dicas: ['Mapa com um X', 'Indiana Jones', 'Bau no fundo do mar'], dif: 30 },
  { resposta: 'Bruxa', dicas: ['Salem', 'Vassoura voadora', 'Joao e Maria'], dif: 30 },
  { resposta: 'Dragao', dicas: ['Daenerys', 'Sao Jorge', 'Smaug'], aceita: ['Dragão'], dif: 25 },
  { resposta: 'Labirinto', dicas: ['Minotauro', 'Dedalo', 'Fio de Ariadne'], dif: 35 },
  { resposta: 'Mascara', dicas: ['Jim Carrey', 'Zorro', 'Veneza'], aceita: ['Máscara'], dif: 30 },
  { resposta: 'Inferno', dicas: ['Dante', 'Nove circulos', 'Enxofre'], dif: 35 },
  { resposta: 'Rei', dicas: ['Elvis Presley', 'Xadrez', 'Luis XIV'], dif: 35 },
  { resposta: 'Advogado', dicas: ['Suits', 'Better Call Saul', 'Juri e toga'], aceita: ['Advogada'], dif: 35 },
  { resposta: 'Naufragio', dicas: ['Titanic', 'Robinson Crusoe', 'Garrafa com bilhete'], aceita: ['Naufrágio'], dif: 40 },

  /* Segunda leva do baralho de palavra-chave. */
  { resposta: 'Aniversario', dicas: ['De Repente 30', 'Milton Nascimento', 'A Morte Te Da Parabens'], aceita: ['Aniversário'], dif: 35 },
  { resposta: 'Cabelo', dicas: ['Sansao', 'Joelma', 'Rapunzel'], dif: 30 },
  { resposta: 'Carro', dicas: ['Need for Speed', 'Ayrton Senna', 'Transformers'], dif: 30 },
  { resposta: 'Rosa', dicas: ['Roger Waters', 'Barbie', 'A Bela e a Fera'], dif: 40 },
  { resposta: 'Baba', dicas: ['Sra. Doubtfire', 'Mary Poppins', 'A Novica Rebelde'], aceita: ['Babá'], dif: 35 },
  { resposta: 'Corvo', dicas: ['Edgar Allan Poe', 'Itachi Uchiha', 'Os Passaros'], dif: 40 },
  { resposta: 'Planeta', dicas: ['Freddie Mercury', 'Bruno Mars', 'Viagem ao Centro da Terra'], dif: 45 },
  { resposta: 'Baleia', dicas: ['Free Willy', 'Pinoquio', 'Moby Dick'], dif: 30 },
  { resposta: 'Profissao', dicas: ['Professor Girafales', 'Dr. House', 'Advogado do Diabo'], aceita: ['Profissão', 'Emprego'], dif: 45 },
  { resposta: 'Azul', dicas: ['Os Smurfs', 'Mistica', 'Avatar'], dif: 30 },
  { resposta: 'Heroi', dicas: ['The Boys', 'Hercules', 'Os Vingadores'], aceita: ['Herói'], dif: 30 },
  { resposta: 'Balao', dicas: ['Simony', 'Pennywise', 'Volta ao mundo'], aceita: ['Balão'], dif: 40 },
  { resposta: 'Amor', dicas: ['Um Lugar Chamado Notting Hill', 'Cupido', 'Romeu e Julieta'], dif: 30 },
  { resposta: 'Letra Z', dicas: ['Zeze di Camargo', 'Zorro', 'Dragon Ball'], aceita: ['Z', 'A letra Z'], dif: 45 },
  { resposta: 'Urso', dicas: ['Ted', 'Ze Colmeia', 'Kung Fu Panda'], dif: 25 },
  { resposta: 'Orfao', dicas: ['Chiquititas', 'Batman', 'Harry Potter'], aceita: ['Órfão', 'Orfa'], dif: 35 },
  { resposta: 'Quarteto', dicas: ['The Rolling Stones', 'Senhor Fantastico', 'Os Trapalhoes'], dif: 45 },
  { resposta: 'Anjo', dicas: ['Camila Queiroz', 'Dulce Maria', 'Lucifer'], dif: 45 },
  { resposta: 'Orelha', dicas: ['Mike Tyson', 'Van Gogh', 'Dumbo'], aceita: ['Ouvido'], dif: 30 },
  { resposta: 'Policia', dicas: ['Brooklyn Nine-Nine', 'Blitz', 'Duro de Matar'], aceita: ['Polícia', 'Policial'], dif: 35 },
  { resposta: 'Cachorro', dicas: ['Pitbull', 'Vira-lata caramelo', '101 Dalmatas'], aceita: ['Cao', 'Cachorra'], dif: 25 },
  { resposta: 'Boneco', dicas: ['Frozen', 'Escolinha do Professor Raimundo', 'Chucky'], dif: 40 },
  { resposta: 'Rainha', dicas: ['Bohemian Rhapsody', 'Xuxa', 'O Diario da Princesa'], dif: 35 },

  /* Cartas novas, no mesmo molde das do baralho. */
  { resposta: 'Castelo', dicas: ['Luis II da Baviera', 'Hogwarts', 'Ponte levadica'], dif: 30 },
  { resposta: 'Torre', dicas: ['Eiffel', 'Pisa', 'Rapunzel'], dif: 30 },
  { resposta: 'Muralha', dicas: ['China', 'Game of Thrones', 'Berlim'], aceita: ['Muro'], dif: 35 },
  { resposta: 'Piramide', dicas: ['Gize', 'Nota de dolar', 'Louvre'], aceita: ['Pirâmide', 'Piramides'], dif: 35 },
  { resposta: 'Raio', dicas: ['Zeus', 'Harry Potter', 'Usain Bolt'], dif: 30 },
  { resposta: 'Terremoto', dicas: ['Escala Richter', 'Japao', 'San Andreas'], dif: 30 },
  { resposta: 'Furacao', dicas: ['Katrina', 'O Magico de Oz', 'Olho no centro'], aceita: ['Furacão'], dif: 40 },
  { resposta: 'Cometa', dicas: ['Halley', 'Fim dos dinossauros', 'Rena do Papai Noel'], dif: 35 },
  { resposta: 'Astronauta', dicas: ['Yuri Gagarin', 'Interestelar', 'Traje branco inflado'], dif: 25 },
  { resposta: 'Alien', dicas: ['Roswell', 'E.T.', 'Homens de Preto'], aceita: ['Extraterrestre', 'Alienigena'], dif: 25 },
  { resposta: 'Lobisomem', dicas: ['Lua cheia', 'Crepusculo', 'Bala de prata'], dif: 25 },
  { resposta: 'Caveira', dicas: ['Bandeira pirata', 'Hamlet', 'Dia dos Mortos'], dif: 30 },
  { resposta: 'Veneno', dicas: ['Socrates', 'Branca de Neve', 'Cobra coral'], dif: 30 },
  { resposta: 'Ferro', dicas: ['Idade dos metais', 'Passar', 'Margaret Thatcher'], dif: 40 },
  { resposta: 'Madeira', dicas: ['Ilha de Portugal', 'Lenhador', 'Pinoquio'], dif: 40 },
  { resposta: 'Sal', dicas: ['Mar Morto', 'Mulher de Lo', 'Gandhi'], dif: 40 },
  { resposta: 'Pao', dicas: ['Ultima Ceia', 'Padaria de manha', 'Fermento'], aceita: ['Pão'], dif: 25 },
  { resposta: 'Cerveja', dicas: ['Oktoberfest', 'Lupulo', 'Homer Simpson'], dif: 25 },
  { resposta: 'Mel', dicas: ['Ursinho Pooh', 'Colmeia', 'Adocante natural'], dif: 30 },
  { resposta: 'Porco', dicas: ['Cofrinho', 'Peppa', 'Chiqueiro na fazenda'], dif: 25 },
  { resposta: 'Aguia', dicas: ['Legiao romana', 'Voa mais alto', 'Simbolo dos Estados Unidos'], aceita: ['Águia'], dif: 35 },
  { resposta: 'Tigre', dicas: ['Shere Khan', 'Sucrilhos', 'Listras laranja'], dif: 25 },
  { resposta: 'Panda', dicas: ['WWF', 'Bambu', 'Zoologico de Pequim'], dif: 25 },
  { resposta: 'Girafa', dicas: ['Pescoco comprido', 'Savana', 'Madagascar'], dif: 25 },
  { resposta: 'Macaco', dicas: ['Darwin', 'King Kong', 'Cipo na floresta'], dif: 25 },
  { resposta: 'Sapo', dicas: ['Principe encantado', 'Girino', 'Coaxa a noite'], dif: 25 },
  { resposta: 'Morcego', dicas: ['Sonar', 'Caverna escura', 'Bruce Wayne'], dif: 30 },
  { resposta: 'Escorpiao', dicas: ['Mortal Kombat', 'Signo de novembro', 'Ferrao na ponta'], aceita: ['Escorpião'], dif: 35 },
  { resposta: 'Crocodilo', dicas: ['Rio Nilo', 'Lagrimas falsas', 'Steve Irwin'], aceita: ['Jacare'], dif: 30 },
  { resposta: 'Golfinho', dicas: ['Flipper', 'Nada em bando', 'Show no aquario'], dif: 30 },
  { resposta: 'Polvo', dicas: ['Oito bracos', 'Tinta preta', 'Paul da Copa'], dif: 30 },
  { resposta: 'Gigante', dicas: ['Golias', 'Pe de feijao', 'Hagrid'], dif: 30 },
  { resposta: 'Anao', dicas: ['Branca de Neve', 'Tyrion Lannister', 'Gimli'], aceita: ['Anão'], dif: 30 },
  { resposta: 'Careca', dicas: ['Vin Diesel', 'Mahatma Gandhi', 'Sr. Limpinho'], dif: 35 },
  { resposta: 'Biblioteca', dicas: ['Alexandria', 'Silencio obrigatorio', 'Estante ate o teto'], dif: 30 },
  { resposta: 'Museu', dicas: ['Louvre', 'Mona Lisa', 'Esqueleto de dinossauro'], dif: 30 },
  { resposta: 'Igreja', dicas: ['Notre-Dame', 'Vaticano', 'Casamento de sabado'], dif: 25 },
  { resposta: 'Trompete', dicas: ['Louis Armstrong', 'Nova Orleans', 'Juizo Final'], aceita: ['Trombeta'], dif: 40 },
  { resposta: 'Microfone', dicas: ['Stand-up', 'Karaoke', 'Reporter na rua'], dif: 30 },
  { resposta: 'Oscar', dicas: ['Estatueta dourada', 'Tapete vermelho', 'Envelope lacrado'], dif: 25 },
  { resposta: 'Nobel', dicas: ['Dinamite', 'Marie Curie', 'Oslo'], dif: 35 },
  { resposta: 'Olimpiadas', dicas: ['Tocha', 'Cinco aneis', 'Atenas 1896'], aceita: ['Olimpíadas', 'Olimpiada', 'Jogos Olimpicos'], dif: 25 },
  { resposta: 'Medalha', dicas: ['Podio', 'Fita no pescoco', 'Hino tocando'], dif: 30 },
  { resposta: 'Juiz', dicas: ['Apito', 'Toga e martelo', 'VAR'], aceita: ['Juiza'], dif: 30 },
  { resposta: 'Principe', dicas: ['Maquiavel', 'Sapo beijado', 'Cinderela'], aceita: ['Príncipe'], dif: 35 },
  { resposta: 'Cavaleiro', dicas: ['Armadura', 'Ordem dos templarios', 'Tavola redonda'], dif: 30 },
  { resposta: 'Ninja', dicas: ['Naruto', 'Tartarugas', 'Sombra e shuriken'], dif: 25 },
  { resposta: 'Viking', dicas: ['Escandinavia', 'Barco longo', 'Capacete com chifre'], aceita: ['Vikings'], dif: 30 },
  { resposta: 'Cowboy', dicas: ['Faroeste', 'Espora e laco', 'Clint Eastwood'], aceita: ['Vaqueiro'], dif: 30 },
  { resposta: 'Beijo', dicas: ['Klimt', 'Judas', 'Sapo'], dif: 35 },
  { resposta: 'Casamento', dicas: ['Vestido branco', 'O Poderoso Chefao', 'Bodas de ouro'], dif: 30 },
  { resposta: 'Estrada', dicas: ['Route 66', 'Kerouac', 'Caminhoneiro'], dif: 35 },
  { resposta: 'Magico', dicas: ['Houdini', 'Coelho na cartola', 'Abracadabra'], aceita: ['Mágico', 'Magica', 'Ilusionista'], dif: 25 },
  { resposta: 'Gravidade', dicas: ['Newton', 'Sandra Bullock', 'Tudo cai'], dif: 35 },
  { resposta: 'Samurai', dicas: ['Japao feudal', 'Katana', 'Codigo de honra'], dif: 30 }
];

module.exports = { PALAVRAS };
