'use strict';

/**
 * Banco de perguntas do PensaRápido.
 *
 * Formato de cada pergunta:
 *   {
 *     pergunta: enunciado mostrado na tela,
 *     resposta: a resposta oficial, digitada pelo jogador no chat,
 *     aceita:   outras formas válidas (opcional) — "Holanda" para "Países Baixos",
 *     dif:      dificuldade inicial de 0 a 100 (opcional, padrão 40),
 *     imagem:   URL de uma imagem (opcional)
 *   }
 *
 * Acentos, maiúsculas, pontuação e espaços são ignorados na comparação, e
 * quem erra menos de 10% da palavra acerta assim mesmo (ver comparar.js).
 *
 * O campo `dif` é só o ponto de partida: o servidor ajusta a dificuldade real
 * conforme as pessoas jogam — quanto menos gente acerta e quanto mais demoram,
 * mais ela sobe (ver dificuldade.js). Dificuldade NÃO altera a pontuação.
 */

const CATEGORIAS = [
  { id: 'bandeiras', nome: 'Bandeiras', icone: '🚩', cor: '#ef4444' },
  { id: 'geografia', nome: 'Geografia', icone: '🌍', cor: '#22c55e' },
  { id: 'matematica', nome: 'Matemática', icone: '🔢', cor: '#3b82f6' },
  { id: 'esportes', nome: 'Esportes', icone: '🏅', cor: '#f97316' },
  { id: 'futebol', nome: 'Futebol', icone: '⚽', cor: '#84cc16' },
  { id: 'anime', nome: 'Anime', icone: '🍥', cor: '#ec4899' },
  { id: 'musica', nome: 'Música', icone: '🎵', cor: '#a855f7' },
  { id: 'cinema', nome: 'Cinema & TV', icone: '🎬', cor: '#eab308' },
  { id: 'historia', nome: 'História', icone: '📜', cor: '#d97706' },
  { id: 'ciencia', nome: 'Ciência', icone: '🔬', cor: '#06b6d4' },
  { id: 'games', nome: 'Games', icone: '🎮', cor: '#8b5cf6' }
];

/* ------------------------------------------------------------------ *
 * Bandeiras: [códigoISO, país]. As imagens vêm do flagcdn.com.
 * ------------------------------------------------------------------ */
const BANDEIRAS = [
  ['br', 'Brasil'],
  ['jp', 'Japão'],
  ['ca', 'Canadá'],
  ['de', 'Alemanha'],
  ['it', 'Itália'],
  ['kr', 'Coreia do Sul'],
  ['gr', 'Grécia'],
  ['ch', 'Suíça'],
  ['au', 'Austrália'],
  ['za', 'África do Sul'],
  ['mx', 'México'],
  ['eg', 'Egito'],
  ['ar', 'Argentina'],
  ['pt', 'Portugal'],
  ['in', 'Índia'],
  ['tr', 'Turquia'],
  ['nl', 'Países Baixos'],
  ['se', 'Suécia'],
  ['ie', 'Irlanda'],
  ['jm', 'Jamaica'],
  ['gb', 'Reino Unido'],
  ['es', 'Espanha'],
  ['cn', 'China'],
  ['ru', 'Rússia'],
  ['no', 'Noruega'],
  ['ke', 'Quênia']
];

/* Variantes aceitas e dificuldade inicial por país. */
const ACEITA_PAIS = {
  'Países Baixos': ['Holanda'],
  'Reino Unido': ['Inglaterra', 'UK', 'Grã-Bretanha'],
  'Coreia do Sul': ['Coreia'],
  'África do Sul': ['Africa do Sul']
};

const DIF_PAIS = {
  'Brasil': 15,
  'Japão': 20,
  'Canadá': 20,
  'Alemanha': 25,
  'Itália': 20,
  'Coreia do Sul': 45,
  'Grécia': 45,
  'Suíça': 45,
  'Austrália': 45,
  'África do Sul': 45,
  'México': 45,
  'Egito': 45,
  'Argentina': 25,
  'Portugal': 25,
  'Índia': 45,
  'Turquia': 45,
  'Países Baixos': 45,
  'Suécia': 45,
  'Irlanda': 45,
  'Jamaica': 60,
  'Reino Unido': 25,
  'Espanha': 30,
  'China': 25,
  'Rússia': 45,
  'Noruega': 45,
  'Quênia': 75
};

const perguntasBandeiras = BANDEIRAS.map(([iso, pais]) => ({
  pergunta: 'De quem é essa bandeira?',
  imagem: `https://flagcdn.com/w320/${iso}.png`,
  resposta: pais,
  aceita: ACEITA_PAIS[pais] || [],
  dif: DIF_PAIS[pais] ?? 45
}));

/* ------------------------------------------------------------------ *
 * Perguntas de letra de música.
 *
 * O campo `letra` faz a pergunta mostrar um trecho em destaque, e o
 * enunciado decide o que se pergunta sobre ele:
 *   - "Qual é o nome desta música?"  -> resposta é o título
 *   - "Quem canta esta música?"      -> resposta é o artista
 *
 * Os trechos abaixo são todos de músicas em domínio público (tradicionais,
 * hinos antigos, canções do século XIX). Para usar músicas atuais, cole o
 * trecho você mesmo seguindo o mesmo formato — eu não incluo letras de
 * músicas protegidas por direito autoral.
 * ------------------------------------------------------------------ */
const LETRAS_MUSICA = [
  { pergunta: 'Qual é o nome desta música?', letra: 'Twinkle, twinkle, little star, how I wonder what you are',
    resposta: 'Twinkle Twinkle Little Star', aceita: ['Twinkle Little Star'], dif: 20 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Amazing grace, how sweet the sound',
    resposta: 'Amazing Grace', dif: 25 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Should auld acquaintance be forgot',
    resposta: 'Auld Lang Syne', dif: 60 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Dashing through the snow in a one-horse open sleigh',
    resposta: 'Jingle Bells', dif: 25 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Silent night, holy night',
    resposta: 'Silent Night', aceita: ['Noite Feliz'], dif: 25 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Row, row, row your boat, gently down the stream',
    resposta: 'Row Row Row Your Boat', dif: 30 },
  { pergunta: 'Qual é o nome desta música?', letra: 'My Bonnie lies over the ocean',
    resposta: 'My Bonnie Lies Over the Ocean', aceita: ['My Bonnie'], dif: 55 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Oh! Susanna, don\u2019t you cry for me',
    resposta: 'Oh Susanna', dif: 45 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Oh, give me a home where the buffalo roam',
    resposta: 'Home on the Range', dif: 60 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Oh Danny Boy, the pipes, the pipes are calling',
    resposta: 'Danny Boy', dif: 45 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Alas, my love, you do me wrong',
    resposta: 'Greensleeves', dif: 65 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Swing low, sweet chariot, coming for to carry me home',
    resposta: 'Swing Low Sweet Chariot', dif: 50 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Take me out to the ball game, take me out with the crowd',
    resposta: 'Take Me Out to the Ball Game', dif: 55 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Oh say, can you see, by the dawn\u2019s early light',
    resposta: 'The Star-Spangled Banner', aceita: ['Star Spangled Banner', 'hino dos Estados Unidos'], dif: 50 },
  { pergunta: 'Qual é o nome desta música?', letra: 'Yankee Doodle went to town, a-riding on a pony',
    resposta: 'Yankee Doodle', dif: 45 },

  { pergunta: 'Qual trompetista ficou famoso pela versão desta música?', letra: 'Oh, when the saints go marching in',
    resposta: 'Louis Armstrong', aceita: ['Armstrong'], dif: 55 },
  { pergunta: 'Qual banda britânica gravou a versão mais famosa desta música, em 1964?',
    letra: 'There is a house in New Orleans, they call the Rising Sun',
    resposta: 'The Animals', aceita: ['Animals'], dif: 60 },
  { pergunta: 'Qual dupla americana popularizou esta canção tradicional em 1966?',
    letra: 'Are you going to Scarborough Fair?',
    resposta: 'Simon & Garfunkel', aceita: ['Simon e Garfunkel', 'Simon and Garfunkel'], dif: 60 }
];

/* ------------------------------------------------------------------ */

const QUESTOES = {
  bandeiras: perguntasBandeiras,

  futebol: [
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Di_stefano_argentina_%28cropped%29.jpg', resposta: 'Alfredo Di Stéfano', aceita: ['Di Stéfano', 'Stéfano'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Raymond_Kopa_1963b.jpg/500px-Raymond_Kopa_1963b.jpg', resposta: 'Raymond Kopa', aceita: ['Kopa'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Luis_Su%C3%A1rez_Miramontes_1962.jpg', resposta: 'Luis Suárez Miramontes', aceita: ['Miramontes', 'Luisito Suárez'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Omar_Sivori.jpg/500px-Omar_Sivori.jpg', resposta: 'Omar Sívori', aceita: ['Sívori'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Josef_Masopust_official_photo.jpg/500px-Josef_Masopust_official_photo.jpg', resposta: 'Josef Masopust', aceita: ['Masopust'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/LevYashin.JPG/500px-LevYashin.JPG', resposta: 'Lev Yashin', aceita: ['Yashin'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Denis_Law_%284x5_cropped%29.jpg/500px-Denis_Law_%284x5_cropped%29.jpg', resposta: 'Denis Law', aceita: ['Law'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Eusebio_en_1973.jpg/500px-Eusebio_en_1973.jpg', resposta: 'Eusébio', aceita: ['Eusébio da Silva Ferreira', 'Pantera Negra'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/LondonHouseAmsterdam1966_Bobby_Charlton.jpg/500px-LondonHouseAmsterdam1966_Bobby_Charlton.jpg', resposta: 'Bobby Charlton', aceita: ['Charlton'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Fl%C3%B3ri%C3%A1n_Albert_cropped.jpg/500px-Fl%C3%B3ri%C3%A1n_Albert_cropped.jpg', resposta: 'Flórián Albert', aceita: ['Albert'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/George_best_1976.jpg/500px-George_best_1976.jpg', resposta: 'George Best', aceita: ['Best'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/7/7d/Rivera.jpg', resposta: 'Gianni Rivera', aceita: ['Rivera'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Gerd_M%C3%BCller_c1973_%28cropped%29.jpg', resposta: 'Gerd Müller', aceita: ['Der Bomber'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Johan_Cruijff_%281974%29.jpg/500px-Johan_Cruijff_%281974%29.jpg', resposta: 'Johan Cruyff', aceita: ['Cruyff'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Franz_Beckenbauer_%281975%29.jpg/500px-Franz_Beckenbauer_%281975%29.jpg', resposta: 'Franz Beckenbauer', aceita: ['Beckenbauer'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/7/74/Oleg_Blokhin2013.jpg', resposta: 'Oleg Blokhin', aceita: ['Blokhin'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Allan_Simonsen_20121027.JPG/500px-Allan_Simonsen_20121027.JPG', resposta: 'Allan Simonsen', aceita: ['Simonsen'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Kevin_keegan_panini_card_%28cropped%29.jpg/500px-Kevin_keegan_panini_card_%28cropped%29.jpg', resposta: 'Kevin Keegan', aceita: ['Keegan'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/2015-02-06_Rummenigge_0370_%28cropped%29.JPG/500px-2015-02-06_Rummenigge_0370_%28cropped%29.JPG', resposta: 'Karl-Heinz Rummenigge', aceita: ['Rummenigge'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Paolo_Rossi_Vicenza.jpg/500px-Paolo_Rossi_Vicenza.jpg', resposta: 'Paolo Rossi', aceita: ['Rossi'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Michel_Platini_2010_%28cropped%29.jpg', resposta: 'Michel Platini', aceita: ['Platini'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Ihor_Belanov.jpeg', resposta: 'Igor Belanov', aceita: ['Belanov'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/25th_Laureus_World_Sports_Awards_-_Ruud_Gullit_-_240422_131911_%28cropped%29.jpg/500px-25th_Laureus_World_Sports_Awards_-_Ruud_Gullit_-_240422_131911_%28cropped%29.jpg', resposta: 'Ruud Gullit', aceita: ['Gullit'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Marco_van_Basten_%282%29_%28cropped%29.jpg', resposta: 'Marco van Basten', aceita: ['van Basten', 'Basten'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2019_Lothar_Matth%C3%A4us.jpg/500px-2019_Lothar_Matth%C3%A4us.jpg', resposta: 'Lothar Matthäus', aceita: ['Matthäus'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/PapinJP1997_%28cropped%29.jpg/500px-PapinJP1997_%28cropped%29.jpg', resposta: 'Jean-Pierre Papin', aceita: ['Papin'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/4/4e/%D8%B1%D9%88%D8%A8%D8%B1%D8%AA%D9%88_%D8%A8%D8%A7%D8%AC%D9%88_%28cropped%29.jpg', resposta: 'Roberto Baggio', aceita: ['Baggio'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Stoichkov_in_2016.jpg/500px-Stoichkov_in_2016.jpg', resposta: 'Hristo Stoichkov', aceita: ['Stoichkov'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/5/53/Clar_Weah%2C_George_Weah%2C_Joe_Biden%2C_Jill_Biden_%28cropped%29.jpg', resposta: 'George Weah', aceita: ['Weah'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Matthias_Sammer_2722.jpg/500px-Matthias_Sammer_2722.jpg', resposta: 'Matthias Sammer', aceita: ['Sammer'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/12.12.2025_%E2%80%93_Cerim%C3%B4nia_de_lan%C3%A7amento_do_SBT_News_-_54980664160_%28cropped2%29.jpg/500px-12.12.2025_%E2%80%93_Cerim%C3%B4nia_de_lan%C3%A7amento_do_SBT_News_-_54980664160_%28cropped2%29.jpg', resposta: 'Ronaldo', aceita: ['Ronaldo Fenômeno', 'Ronaldo Nazário'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg', resposta: 'Zinedine Zidane', aceita: ['Zidane', 'Zizou'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Rivaldo.jpg', resposta: 'Rivaldo', aceita: ['Rivaldo Vítor Borba Ferreira', 'Rivaldo Ferreira'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Luis_Figo_2023.jpg/500px-Luis_Figo_2023.jpg', resposta: 'Luís Figo', aceita: ['Figo'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Michael_Owen.jpg/500px-Michael_Owen.jpg', resposta: 'Michael Owen', aceita: ['Owen'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Pavel_Nedv%C4%9Bd.jpg/500px-Pavel_Nedv%C4%9Bd.jpg', resposta: 'Pavel Nedvěd', aceita: ['Nedvěd'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/2/25/%D0%90%D0%BD%D0%B4%D1%80%D1%96%D0%B9_%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%BE_2024_%28cropped%29.png', resposta: 'Andriy Shevchenko', aceita: ['Shevchenko'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ronaldinho_in_2019.jpg/500px-Ronaldinho_in_2019.jpg', resposta: 'Ronaldinho', aceita: ['Ronaldinho Gaúcho'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Fabio_Cannavaro_2011.jpg/500px-Fabio_Cannavaro_2011.jpg', resposta: 'Fabio Cannavaro', aceita: ['Cannavaro'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Kak%C3%A1_visited_Stadium_St._Petersburg.jpg/500px-Kak%C3%A1_visited_Stadium_St._Petersburg.jpg', resposta: 'Kaká', aceita: ['Ricardo Izecson dos Santos Leite', 'Ricardo Kaká'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg/500px-Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_%28cropped%29.jpg', resposta: 'Cristiano Ronaldo', aceita: ['CR7', 'Cristiano'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg/500px-Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg', resposta: 'Lionel Messi', aceita: ['Messi', 'Leo Messi'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Luka_Modric_Croatia_v_Portugal_2_July_2026-055.jpg/500px-Luka_Modric_Croatia_v_Portugal_2_July_2026-055.jpg', resposta: 'Luka Modrić', aceita: ['Modrić'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Karim_Benzema_Pick.jpg/500px-Karim_Benzema_Pick.jpg', resposta: 'Karim Benzema', aceita: ['Benzema'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Rodri_Argentina_v_Spain_19_July_2026-187_%28cropped%29.jpg/500px-Rodri_Argentina_v_Spain_19_July_2026-187_%28cropped%29.jpg', resposta: 'Rodri', aceita: ['Rodrigo Hernández', 'Rodrigo Hernández Cascante'], dif: 45 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg/500px-Neymar_Junior_Brazil_V_Morocco_13_June_2026-40.jpg', resposta: 'Neymar', aceita: ['Neymar Jr', 'Neymar Júnior'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg/500px-Kylian_Mbappe_France_v_Senegal_16_June_2026-391_%28cropped%29.jpg', resposta: 'Kylian Mbappé', aceita: ['Mbappé'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg/500px-2019147183134_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0228_-_B70I8527_%28cropped%29.jpg', resposta: 'Robert Lewandowski', aceita: ['Lewandowski'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Mohamed_Salah_Argentina_v_Egypt_7_July_2026-163_%28cropped%29.jpg/500px-Mohamed_Salah_Argentina_v_Egypt_7_July_2026-163_%28cropped%29.jpg', resposta: 'Mohamed Salah', aceita: ['Salah'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg/500px-Sadio_Mane_France_v_Senegal_16_June_2026-450.jpg', resposta: 'Sadio Mané', aceita: ['Mané'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg/500px-Kevin_De_Bruyne_USMNT_v_Belgium_Mar_28_2026-64_%28cropped%29.jpg', resposta: 'Kevin De Bruyne', aceita: ['De Bruyne', 'Bruyne'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/20160604_AUT_NED_8876_%28cropped%29.jpg/500px-20160604_AUT_NED_8876_%28cropped%29.jpg', resposta: 'Virgil van Dijk', aceita: ['van Dijk', 'Dijk'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/4/4b/Sergio_Ramos_Interview_2021_%28cropped%29.jpg', resposta: 'Sergio Ramos', aceita: ['Ramos'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Gerard_Piqu%C3%A9_Euro_2012_vs_France_01.jpg', resposta: 'Gerard Piqué', aceita: ['Piqué'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Andr%C3%A9s_Iniesta_Argentina_v_Spain_19_July_2026-034_%28cropped%29.jpg/500px-Andr%C3%A9s_Iniesta_Argentina_v_Spain_19_July_2026-034_%28cropped%29.jpg', resposta: 'Andrés Iniesta', aceita: ['Iniesta'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/Xavi%2C_Persepolis_vs._Al_Sadd%2C_20190520_02_%28cropped%29.jpg', resposta: 'Xavi', aceita: ['Xavi Hernández', 'Xavier Hernández'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Premios_Goya_2020_-_Carles_Pujol.jpg/500px-Premios_Goya_2020_-_Carles_Pujol.jpg', resposta: 'Carles Puyol', aceita: ['Puyol'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Iker-Casillas-SportsTrade-2021-cropped.jpg/500px-Iker-Casillas-SportsTrade-2021-cropped.jpg', resposta: 'Iker Casillas', aceita: ['Casillas'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/a/a4/Spain-Tahiti%2C_Confederations_Cup_2013_%2802%29_%28Villa_crop%29.jpg', resposta: 'David Villa', aceita: ['Villa'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/5/57/Fernando_Torres_2017.jpg', resposta: 'Fernando Torres', aceita: ['Torres'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/2023_-_Cesc_Fabregas_%28cropped%29.jpg/500px-2023_-_Cesc_Fabregas_%28cropped%29.jpg', resposta: 'Cesc Fàbregas', aceita: ['Fàbregas'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/David_Silva_2017.jpg/500px-David_Silva_2017.jpg', resposta: 'David Silva', aceita: ['David Jiménez Silva'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Sergio_Busquets_NYCFC_Miami_24_Sep_2025-020_%28cropped%29.jpg/500px-Sergio_Busquets_NYCFC_Miami_24_Sep_2025-020_%28cropped%29.jpg', resposta: 'Sergio Busquets', aceita: ['Busquets'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Thiago_Alcantara_13_%28cropped%29.jpg/500px-UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Thiago_Alcantara_13_%28cropped%29.jpg', resposta: 'Thiago Alcântara', aceita: ['Alcântara', 'Thiago'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/3/32/Liver-RM_%285%29_%28cropped%29.jpg', resposta: 'Isco', aceita: ['Francisco Román Alarcón', 'Isco Alarcón'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Marco_Asensio_10_Fenerbah%C3%A7e_20260805_%284%29_%28cropped%29.JPG/500px-Marco_Asensio_10_Fenerbah%C3%A7e_20260805_%284%29_%28cropped%29.JPG', resposta: 'Marco Asensio', aceita: ['Asensio'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/2022_FIFA_World_Cup_United_States_1%E2%80%931_Wales_-_%2832%29_2.png/500px-2022_FIFA_World_Cup_United_States_1%E2%80%931_Wales_-_%2832%29_2.png', resposta: 'Gareth Bale', aceita: ['Bale'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Luis_Su%C3%A1rez_2026_%28cropped%29.jpg/500px-Luis_Su%C3%A1rez_2026_%28cropped%29.jpg', resposta: 'Luis Suárez', aceita: ['Suárez'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/PALMEIRAS_X_BOCA_JUNIORS_-_COPA_LIBERTADORES_2023_-_53286889335_%28cropped_2%29.jpg/500px-PALMEIRAS_X_BOCA_JUNIORS_-_COPA_LIBERTADORES_2023_-_53286889335_%28cropped_2%29.jpg', resposta: 'Edinson Cavani', aceita: ['Cavani'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Diego_God%C3%ADn_2018_%28cropped%29.jpg', resposta: 'Diego Godín', aceita: ['Godín'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Radamel_Falcao_Garc%C3%ADa_en_Millonarios.jpg/500px-Radamel_Falcao_Garc%C3%ADa_en_Millonarios.jpg', resposta: 'Radamel Falcao', aceita: ['Falcao'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Argentina_-_Colombia_2022_%2828%29_%28cropped_2%29.jpg/500px-Argentina_-_Colombia_2022_%2828%29_%28cropped_2%29.jpg', resposta: 'James Rodríguez', aceita: ['Rodríguez'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Juan_Cuadrado_2019_%28cropped%29.jpg', resposta: 'Juan Cuadrado', aceita: ['Cuadrado'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Arturo_Vidal_Copiap%C3%B3_v_Colo-Colo_20241110_13.jpg/500px-Arturo_Vidal_Copiap%C3%B3_v_Colo-Colo_20241110_13.jpg', resposta: 'Arturo Vidal', aceita: ['Vidal'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Alexis_S%C3%A1nchez_2017.jpg/500px-Alexis_S%C3%A1nchez_2017.jpg', resposta: 'Alexis Sánchez', aceita: ['Sánchez'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Manuel_Neuer_Ecuador_v_Germany_25_June_2026-148.jpg/500px-Manuel_Neuer_Ecuador_v_Germany_25_June_2026-148.jpg', resposta: 'Manuel Neuer', aceita: ['Neuer'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/FC_Red_Bull_Salzburg_gegen_Bayern_M%C3%BCnchen_%282025-01-06_Testspiel%29_19.jpg/500px-FC_Red_Bull_Salzburg_gegen_Bayern_M%C3%BCnchen_%282025-01-06_Testspiel%29_19.jpg', resposta: 'Thomas Müller', aceita: ['Thomas Muller'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Philipp_Lahm_auf_der_Berlinale_2024%2C_Ausschnitt.jpg/500px-Philipp_Lahm_auf_der_Berlinale_2024%2C_Ausschnitt.jpg', resposta: 'Philipp Lahm', aceita: ['Lahm'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Re-publica_23_-_Tag_3_%2852957826298%29_%28cropped%29.jpg/500px-Re-publica_23_-_Tag_3_%2852957826298%29_%28cropped%29.jpg', resposta: 'Bastian Schweinsteiger', aceita: ['Schweinsteiger'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Mesut_%C3%96zil_at_Baku_before_2019_UEFA_Europe_League_Final.jpg/500px-Mesut_%C3%96zil_at_Baku_before_2019_UEFA_Europe_League_Final.jpg', resposta: 'Mesut Özil', aceita: ['Özil'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Toni_Kroos_Real_Madrid_2021.jpg/500px-Toni_Kroos_Real_Madrid_2021.jpg', resposta: 'Toni Kroos', aceita: ['Kroos'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93126.jpg/500px-2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93126.jpg', resposta: 'Marco Reus', aceita: ['Reus'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93103.jpg/500px-2023-08-12_TSV_Schott_Mainz_gegen_Borussia_Dortmund_%28DFB-Pokal_2023-24%29_by_Sandro_Halank%E2%80%93103.jpg', resposta: 'Mats Hummels', aceita: ['Hummels'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Jerome_Boateng_Training_2019-04-10_FC_Bayern_Muenchen-2_%28cropped%29.jpg/500px-Jerome_Boateng_Training_2019-04-10_FC_Bayern_Muenchen-2_%28cropped%29.jpg', resposta: 'Jérôme Boateng', aceita: ['Boateng'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/2016209185719_2016-07-27_Champions_for_Charity_-_Sven_-_1D_X_-_0149_-_DV3P4742_mod.jpg/500px-2016209185719_2016-07-27_Champions_for_Charity_-_Sven_-_1D_X_-_0149_-_DV3P4742_mod.jpg', resposta: 'Miroslav Klose', aceita: ['Klose'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/20180602_FIFA_Friendly_Match_Austria_vs._Germany_%C4%B0lkay_G%C3%BCndo%C4%9Fan_850_0728.jpg/500px-20180602_FIFA_Friendly_Match_Austria_vs._Germany_%C4%B0lkay_G%C3%BCndo%C4%9Fan_850_0728.jpg', resposta: 'İlkay Gündoğan', aceita: ['Gündoğan'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Leroy_Sane_Ecuador_v_Germany_25_June_2026-119_%28cropped%29.jpg/500px-Leroy_Sane_Ecuador_v_Germany_25_June_2026-119_%28cropped%29.jpg', resposta: 'Leroy Sané', aceita: ['Sané'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3684_by_Stepro.jpg/500px-2020-03-10_Fu%C3%9Fball%2C_M%C3%A4nner%2C_UEFA_Champions_League_Achtelfinale%2C_RB_Leipzig_-_Tottenham_Hotspur_1DX_3684_by_Stepro.jpg', resposta: 'Timo Werner', aceita: ['Werner'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/FRA-ARG_%2810%29_%28cropped%29.jpg/500px-FRA-ARG_%2810%29_%28cropped%29.jpg', resposta: 'Antoine Griezmann', aceita: ['Griezmann'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Paul_Pogba_at_the_2025_Cannes_Film_Festival_02.jpg/500px-Paul_Pogba_at_the_2025_Cannes_Film_Festival_02.jpg', resposta: 'Paul Pogba', aceita: ['Pogba'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/N%27Golo_Kante_France_v_Senegal_16_June_2026-397.jpg/500px-N%27Golo_Kante_France_v_Senegal_16_June_2026-397.jpg', resposta: 'N\'Golo Kanté', aceita: ['Kanté'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Lloris_2018_%28cropped%29.jpg/500px-Lloris_2018_%28cropped%29.jpg', resposta: 'Hugo Lloris', aceita: ['Lloris'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Liver-RM_%288%29_%28Varane%29.jpg', resposta: 'Raphaël Varane', aceita: ['Varane'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Olivier_Giroud_December_2024.png', resposta: 'Olivier Giroud', aceita: ['Giroud'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Franck_Ribery_2019_%28cropped%29.jpg/500px-Franck_Ribery_2019_%28cropped%29.jpg', resposta: 'Franck Ribéry', aceita: ['Ribéry'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Ousmane_Dembele_France_v_Senegal_16_June_2026-341_%28cropped%29_2.jpg/500px-Ousmane_Dembele_France_v_Senegal_16_June_2026-341_%28cropped%29_2.jpg', resposta: 'Ousmane Dembélé', aceita: ['Dembélé'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Zlatan_Ibrahimovi%C4%87_nyc.jpg/500px-Zlatan_Ibrahimovi%C4%87_nyc.jpg', resposta: 'Zlatan Ibrahimović', aceita: ['Ibrahimović', 'Zlatan'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/20150616_-_Portugal_-_Italie_-_Gen%C3%A8ve_-_Andrea_Pirlo_%28cropped%29.jpg', resposta: 'Andrea Pirlo', aceita: ['Pirlo'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Norway_Italy_-_June_2025_A_44_%28Gianluigi_Buffon%29.jpg/500px-Norway_Italy_-_June_2025_A_44_%28Gianluigi_Buffon%29.jpg', resposta: 'Gianluigi Buffon', aceita: ['Buffon'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Chiellini_Mancini_Gravina_Mattarella_2021_%28Giorgio_Chiellini%29.jpg', resposta: 'Giorgio Chiellini', aceita: ['Chiellini'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/20150616_-_Portugal_-_Italie_-_Gen%C3%A8ve_-_Leonardo_Bonucci_%28cropped_2%29.jpg', resposta: 'Leonardo Bonucci', aceita: ['Bonucci'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Verratti-2019-07-17_SG_Dynamo_Dresden_vs._Paris_Saint-Germain_by_Sandro_Halank%E2%80%93126.jpg/500px-Verratti-2019-07-17_SG_Dynamo_Dresden_vs._Paris_Saint-Germain_by_Sandro_Halank%E2%80%93126.jpg', resposta: 'Marco Verratti', aceita: ['Verratti'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Ciro_Immobile_20240803_%28cropped%29.jpg/500px-Ciro_Immobile_20240803_%28cropped%29.jpg', resposta: 'Ciro Immobile', aceita: ['Immobile'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/6/60/Lorenzo_Insigne_2021.jpg', resposta: 'Lorenzo Insigne', aceita: ['Insigne'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Wayne_Rooney_%2850121495731%29_%28cropped%29.jpg/500px-Wayne_Rooney_%2850121495731%29_%28cropped%29.jpg', resposta: 'Wayne Rooney', aceita: ['Rooney'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Steven_Gerrard_2018.jpg', resposta: 'Steven Gerrard', aceita: ['Gerrard'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Frank_Lampard_2019.jpg', resposta: 'Frank Lampard', aceita: ['Lampard'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/John_Terry_at_pro-am_Wentworth_golf_course_September_2023_%28cropped%29.jpg/500px-John_Terry_at_pro-am_Wentworth_golf_course_September_2023_%28cropped%29.jpg', resposta: 'John Terry', aceita: ['Terry'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg/500px-Harry_Kane_England_v_Ghana_23_June_2026-219_%28cropped%29.jpg', resposta: 'Harry Kane', aceita: ['Kane'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Raheem_Sterling_-_USA_vs_ENG_-_FIFA_WC_2022_%28cropped%29.jpg', resposta: 'Raheem Sterling', aceita: ['Sterling'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Jordan_Henderson_England_v_Ghana_23_June_2026-029_%28cropped%29.jpg/500px-Jordan_Henderson_England_v_Ghana_23_June_2026-029_%28cropped%29.jpg', resposta: 'Jordan Henderson', aceita: ['Henderson'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Marcus_Rashford_England_v_Ghana_23_June_2026-073.jpg/500px-Marcus_Rashford_England_v_Ghana_23_June_2026-073.jpg', resposta: 'Marcus Rashford', aceita: ['Rashford'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Jamie_Vardy_2018_%28cropped%29.jpg/500px-Jamie_Vardy_2018_%28cropped%29.jpg', resposta: 'Jamie Vardy', aceita: ['Vardy'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/2020-03-10_Dele_Alli_%28cropped%29.jpg/500px-2020-03-10_Dele_Alli_%28cropped%29.jpg', resposta: 'Dele Alli', aceita: ['Alli'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/4/46/Eden_Hazard_at_Baku_before_2019_UEFA_Europe_League_Final.jpg', resposta: 'Eden Hazard', aceita: ['Hazard'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Romelu_Lukaku_2021.jpg/500px-Romelu_Lukaku_2021.jpg', resposta: 'Romelu Lukaku', aceita: ['Lukaku'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Thibaut_Courtois_at_the_2018_World_Cup_%28cropped%29.jpg', resposta: 'Thibaut Courtois', aceita: ['Courtois'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/4/46/Vincent_Kompany_Bayern_Munich_%28cropped%29.jpg', resposta: 'Vincent Kompany', aceita: ['Kompany'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Mertens_2018_%28cropped%29.jpg/500px-Mertens_2018_%28cropped%29.jpg', resposta: 'Dries Mertens', aceita: ['Mertens'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/2019147183036_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0196_-_B70I8495_%28cropped%29.jpg/500px-2019147183036_2019-05-27_Fussball_1.FC_Kaiserslautern_vs_FC_Bayern_M%C3%BCnchen_-_Sven_-_1D_X_MK_II_-_0196_-_B70I8495_%28cropped%29.jpg', resposta: 'Arjen Robben', aceita: ['Robben'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Wesley_Sneijder_at_Sports_Festival_2025.jpg/500px-Wesley_Sneijder_at_Sports_Festival_2025.jpg', resposta: 'Wesley Sneijder', aceita: ['Sneijder'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Loco-Fener_%2810%29.jpg', resposta: 'Robin van Persie', aceita: ['van Persie', 'Persie'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Memphis_Depay_2019.jpg', resposta: 'Memphis Depay', aceita: ['Depay', 'Memphis'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/4/42/%D0%9C%D0%B0%D1%82%D1%87_%C2%AB%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%BE%C2%BB_-_%C2%AB%D0%91%D0%B0%D1%80%D1%81%D0%B5%D0%BB%D0%BE%D0%BD%D0%B0%C2%BB_0-1._2_%D0%BD%D0%BE%D1%8F%D0%B1%D1%80%D1%8F_2021_%D0%B3%D0%BE%D0%B4%D0%B0._II_%E2%80%94_1289671_%28cropped%29.jpg', resposta: 'Frenkie de Jong', aceita: ['de Jong', 'Jong'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/c/c9/2022-07-30_Fu%C3%9Fball%2C_M%C3%A4nner%2C_DFL-Supercup%2C_RB_Leipzig_-_FC_Bayern_M%C3%BCnchen_Matthijs_de_Ligt_%28cropped%29.jpg', resposta: 'Matthijs de Ligt', aceita: ['de Ligt', 'Ligt'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Thiago_Silva_850_1582.jpg/500px-20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Thiago_Silva_850_1582.jpg', resposta: 'Thiago Silva', aceita: ['Thiago Emiliano da Silva'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/07_07_2019_Final_da_Copa_Am%C3%A9rica_2019_%2848226649586%29_%28cropped%29.jpg', resposta: 'Dani Alves', aceita: ['Alves'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Marcelo_Vieira_in_2022.jpg/500px-Marcelo_Vieira_in_2022.jpg', resposta: 'Marcelo', aceita: ['Marcelo Vieira', 'Marcelo Vieira da Silva'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/David_Luiz_at_Baku_before_2019_UEFA_Europe_League_Final.jpg/500px-David_Luiz_at_Baku_before_2019_UEFA_Europe_League_Final.jpg', resposta: 'David Luiz', aceita: ['Luiz'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/20141118_AUTBRA_5022.jpg', resposta: 'Oscar', aceita: ['Oscar dos Santos', 'Oscar Emboaba'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Willian_20042025_%282%29.jpg/500px-Willian_20042025_%282%29.jpg', resposta: 'Willian', aceita: ['Willian Borges', 'Willian Borges da Silva'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Roberto_Firmino_850_1557.jpg/500px-20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Roberto_Firmino_850_1557.jpg', resposta: 'Roberto Firmino', aceita: ['Firmino'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Gabriel_Jesus_850_1688.jpg/500px-20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Gabriel_Jesus_850_1688.jpg', resposta: 'Gabriel Jesus', aceita: ['Jesus'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Casemiro_Brazil_V_Morocco_13_June_2026-76_%28cropped%29.jpg/500px-Casemiro_Brazil_V_Morocco_13_June_2026-76_%28cropped%29.jpg', resposta: 'Casemiro', aceita: ['Carlos Henrique Casimiro', 'Casimiro'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Alisson_Becker_Brazil_V_Morocco_13_June_2026-117_%28cropped%29.jpg/500px-Alisson_Becker_Brazil_V_Morocco_13_June_2026-117_%28cropped%29.jpg', resposta: 'Alisson', aceita: ['Alisson Becker'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Ederson_Brazil_V_Morocco_13_June_2026-14_%28cropped%29.jpg/500px-Ederson_Brazil_V_Morocco_13_June_2026-14_%28cropped%29.jpg', resposta: 'Ederson', aceita: ['Ederson Moraes', 'Ederson Santana de Moraes'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Philippe_Coutinho_850_1692.jpg/500px-20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Philippe_Coutinho_850_1692.jpg', resposta: 'Philippe Coutinho', aceita: ['Coutinho'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Douglas_Costa_%28BRA%29_850_1486_%28cropped%29.jpg/500px-20180610_FIFA_Friendly_Match_Austria_vs._Brazil_Douglas_Costa_%28BRA%29_850_1486_%28cropped%29.jpg', resposta: 'Douglas Costa', aceita: ['Douglas Costa de Souza'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Spar-Zen2015_%283%29.jpg/500px-Spar-Zen2015_%283%29.jpg', resposta: 'Hulk', aceita: ['Givanildo Vieira de Sousa', 'Givanildo Vieira'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Iran_and_Spain_match_at_the_FIFA_World_Cup_23.jpg/500px-Iran_and_Spain_match_at_the_FIFA_World_Cup_23.jpg', resposta: 'Diego Costa', aceita: ['Diego da Silva Costa'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/NIG-ARG_%285%29.jpg/500px-NIG-ARG_%285%29.jpg', resposta: 'Ángel Di María', aceita: ['Di María', 'María'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Javier_Mascherano_NE_Revolution_Inter_Miami_7.9.25-040_%28cropped%29.jpg/500px-Javier_Mascherano_NE_Revolution_Inter_Miami_7.9.25-040_%28cropped%29.jpg', resposta: 'Javier Mascherano', aceita: ['Mascherano'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Gonzalo_Higua%C3%ADn_2019.jpg', resposta: 'Gonzalo Higuaín', aceita: ['Higuaín'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Ag%C3%BCero_in_2018.jpg/500px-Ag%C3%BCero_in_2018.jpg', resposta: 'Sergio Agüero', aceita: ['Agüero'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/%D0%9C%D0%B0%D1%82%D1%87_%C2%AB%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%BE%C2%BB_-_%C2%AB%D0%AE%D0%B2%D0%B5%D0%BD%D1%82%D1%83%D1%81%C2%BB_0-2._20_%D0%BE%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8F_2020_%D0%B3%D0%BE%D0%B4%D0%B0_%E2%80%94_1153905_%28cropped%29.jpg', resposta: 'Paulo Dybala', aceita: ['Dybala'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Lautaro_Martinez_Argentina_v_Spain_19_July_2026-049_%28cropped%29.jpg/500px-Lautaro_Martinez_Argentina_v_Spain_19_July_2026-049_%28cropped%29.jpg', resposta: 'Lautaro Martínez', aceita: ['Lautaro', 'El Toro'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Emiliano_Martinez_Argentina_v_Spain_19_July_2026-269.jpg/500px-Emiliano_Martinez_Argentina_v_Spain_19_July_2026-269.jpg', resposta: 'Emiliano Martínez', aceita: ['Dibu Martínez', 'Dibu'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Keylor_Navas_2018_%28cropped%29.jpg', resposta: 'Keylor Navas', aceita: ['Navas'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg/500px-Christian_Pulisic_USMNT_v_Belgium_Mar_28_2026-73_%28cropped%29.jpg', resposta: 'Christian Pulisic', aceita: ['Pulisic'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg/500px-BFA_2023_-2_Heung-Min_Son_%28cropped%29.jpg', resposta: 'Son Heung-min', aceita: ['Heung-min'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Mahrez_2021.jpg/500px-Mahrez_2021.jpg', resposta: 'Riyad Mahrez', aceita: ['Mahrez'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/1_Pierre-Emerick_Aubameyang_%28cropped%29.jpg/500px-1_Pierre-Emerick_Aubameyang_%28cropped%29.jpg', resposta: 'Pierre-Emerick Aubameyang', aceita: ['Aubameyang'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Yaya_Tour%C3%A9_%28cropped%29.jpg/500px-Yaya_Tour%C3%A9_%28cropped%29.jpg', resposta: 'Yaya Touré', aceita: ['Touré'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Didier_Drogba_%282019%29_%28cropped2%29.jpg/500px-Didier_Drogba_%282019%29_%28cropped2%29.jpg', resposta: 'Didier Drogba', aceita: ['Drogba'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Sammuel_Eto%27o_Fils_02.jpg/500px-Sammuel_Eto%27o_Fils_02.jpg', resposta: 'Samuel Eto\'o', aceita: ['Eto\'o'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Kalidou_Koulibaly_France_v_Senegal_16_June_2026-370_%28cropped%29.jpg/500px-Kalidou_Koulibaly_France_v_Senegal_16_June_2026-370_%28cropped%29.jpg', resposta: 'Kalidou Koulibaly', aceita: ['Koulibaly'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg/500px-Achraf_Hakimi_Morocco_v_Norway_7_June_2026-16.jpg', resposta: 'Achraf Hakimi', aceita: ['Hakimi'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg/500px-Erling_Haaland_Morocco_v_Norway_7_June_2026-51.jpg', resposta: 'Erling Haaland', aceita: ['Haaland'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Manchester_United_v_Liverpool%2C_22_August_2022_%2833%29_%28cropped%29.jpg/500px-Manchester_United_v_Liverpool%2C_22_August_2022_%2833%29_%28cropped%29.jpg', resposta: 'Jadon Sancho', aceita: ['Sancho'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/5/5d/Trent_Alexander-Arnold_2018_%28cropped%29.jpg', resposta: 'Trent Alexander-Arnold', aceita: ['Alexander-Arnold'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Andy_Robertson_Scotland_v_Bolivia_6_June_2026-43.jpg/500px-Andy_Robertson_Scotland_v_Bolivia_6_June_2026-43.jpg', resposta: 'Andrew Robertson', aceita: ['Robertson'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Bernardo_Silva_Croatia_v_Portugal_2_July_2026-238.jpg/500px-Bernardo_Silva_Croatia_v_Portugal_2_July_2026-238.jpg', resposta: 'Bernardo Silva', aceita: ['Bernardo Mota Veiga de Carvalho e Silva'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Bruno_Fernandes_USMNT_v_Portugal_Mar_31_2026-27_%28cropped%29.jpg/500px-Bruno_Fernandes_USMNT_v_Portugal_Mar_31_2026-27_%28cropped%29.jpg', resposta: 'Bruno Fernandes', aceita: ['Fernandes'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Diogo_Costa_Ruben_Dias_Croatia_v_Portugal_2_July_2026-181_%28cropped%29.jpg/500px-Diogo_Costa_Ruben_Dias_Croatia_v_Portugal_2_July_2026-181_%28cropped%29.jpg', resposta: 'Rúben Dias', aceita: ['Dias'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Joao_Felix_Croatia_v_Portugal_2_July_2026-007.jpg/500px-Joao_Felix_Croatia_v_Portugal_2_July_2026-007.jpg', resposta: 'João Félix', aceita: ['Félix'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/5/55/Pepe_2018.jpg', resposta: 'Pepe', aceita: ['Képler Laveran Lima Ferreira', 'Képler Ferreira'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/New_Zealand-Portugal_Nani.jpg/500px-New_Zealand-Portugal_Nani.jpg', resposta: 'Nani', aceita: ['Luís Carlos Almeida da Cunha', 'Luís Almeida da Cunha'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/b/be/Ricardo_Quaresma_%28cropped%29_2.jpg', resposta: 'Ricardo Quaresma', aceita: ['Quaresma'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/20150331_2026_AUT_BIH_2177_Edin_D%C5%BEeko_%28cropped%29.jpg/500px-20150331_2026_AUT_BIH_2177_Edin_D%C5%BEeko_%28cropped%29.jpg', resposta: 'Edin Džeko', aceita: ['Džeko'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Miralem_Pjani%C4%87_2025.jpg', resposta: 'Miralem Pjanić', aceita: ['Pjanić'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Nemanja_Mati%C4%87_2018_%28cropped%29.jpg', resposta: 'Nemanja Matić', aceita: ['Matić'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Granit_Xhaka_%28cropped%29.jpg/500px-Granit_Xhaka_%28cropped%29.jpg', resposta: 'Granit Xhaka', aceita: ['Xhaka'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/0/07/Aleksandar_Kolarov_2018.jpg', resposta: 'Aleksandar Kolarov', aceita: ['Kolarov'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Ivan_Rakiti%C4%87_2020_%28cropped%29.jpg', resposta: 'Ivan Rakitić', aceita: ['Rakitić'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Mario_Mand%C5%BEuki%C4%87_in_2018.jpg/500px-Mario_Mand%C5%BEuki%C4%87_in_2018.jpg', resposta: 'Mario Mandžukić', aceita: ['Mandžukić'], dif: 50 },
    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Lovren_in_Zenit_%28cropped%29.jpg/500px-Lovren_in_Zenit_%28cropped%29.jpg', resposta: 'Dejan Lovren', aceita: ['Lovren'], dif: 50 },

    { pergunta: 'Quem é este jogador?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Stanley_Matthews_1962_%28crop%29.jpg/500px-Stanley_Matthews_1962_%28crop%29.jpg', resposta: 'Stanley Matthews', aceita: ['Matthews', 'Sir Stanley Matthews'], dif: 65 },
    { pergunta: 'Quem é esta jogadora?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/AHegerberg.jpg', resposta: 'Ada Hegerberg', aceita: ['Hegerberg'], dif: 70 },
    { pergunta: 'Quem é esta jogadora?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Megan_Rapinoe_%2848675274817%29_%28cropped%29.jpg/500px-Megan_Rapinoe_%2848675274817%29_%28cropped%29.jpg', resposta: 'Megan Rapinoe', aceita: ['Rapinoe'], dif: 60 },
    { pergunta: 'Quem é esta jogadora?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/UWCL_2025-26_Final_C16.jpg/500px-UWCL_2025-26_Final_C16.jpg', resposta: 'Alexia Putellas', aceita: ['Putellas'], dif: 60 },
    { pergunta: 'Quem é esta jogadora?', imagem: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/25th_Laureus_World_Sports_Awards_-_240422_214032.jpg/500px-25th_Laureus_World_Sports_Awards_-_240422_214032.jpg', resposta: 'Aitana Bonmatí', aceita: ['Bonmatí'], dif: 60 }
  ],

  geografia: [
    { pergunta: 'Qual é a capital da Austrália?', resposta: 'Camberra', aceita: ['Canberra'], dif: 35 },
    { pergunta: 'Qual é o maior deserto quente do mundo?', resposta: 'Saara', dif: 35 },
    { pergunta: 'Qual rio tem o maior volume de água do mundo?', resposta: 'Amazonas', dif: 35 },
    { pergunta: 'Em qual continente fica o Egito?', resposta: 'África', dif: 35 },
    { pergunta: 'Qual é o menor país do mundo em área?', resposta: 'Vaticano', dif: 35 },
    { pergunta: 'Qual é a capital do Canadá?', resposta: 'Ottawa', dif: 35 },
    { pergunta: 'Qual é a montanha mais alta do mundo?', resposta: 'Monte Everest', aceita: ['Everest'], dif: 35 },
    { pergunta: 'Qual país é conhecido como "Terra do Sol Nascente"?', resposta: 'Japão', dif: 20 },
    { pergunta: 'Qual é o maior oceano do planeta?', resposta: 'Pacífico', dif: 35 },
    { pergunta: 'Qual estado brasileiro tem a maior área territorial?', resposta: 'Amazonas', dif: 35 },
    { pergunta: 'Qual é a capital da Argentina?', resposta: 'Buenos Aires', dif: 35 },
    { pergunta: 'Em qual país fica Machu Picchu?', resposta: 'Peru', dif: 35 },
    { pergunta: 'Qual é o maior país do mundo em área?', resposta: 'Rússia', dif: 35 },
    { pergunta: 'Qual cidade é cortada pelo Rio Sena?', resposta: 'Paris', dif: 35 },
    { pergunta: 'Qual país tem o formato parecido com uma bota?', resposta: 'Itália', dif: 20 },
    { pergunta: 'Quantos estados o Brasil tem, sem contar o Distrito Federal?', resposta: '26', dif: 35 },
    { pergunta: 'Qual país africano tem a maior população?', resposta: 'Nigéria', dif: 35 },
    { pergunta: 'Qual é a capital da Espanha?', resposta: 'Madri', dif: 35 },
    { pergunta: 'Qual linha imaginária divide a Terra nos hemisférios norte e sul?', resposta: 'Linha do Equador', aceita: ['Equador'], dif: 35 },
    { pergunta: 'Em qual cidade fica o Coliseu?', resposta: 'Roma', dif: 35 },
    { pergunta: 'Qual é o continente mais populoso do mundo?', resposta: 'Ásia', dif: 35 },
    { pergunta: 'Qual é a capital do Japão?', resposta: 'Tóquio', dif: 35 }
  ],

  matematica: [
    { pergunta: 'Quanto é 7 × 8?', resposta: '56', dif: 10 },
    { pergunta: 'Qual o valor de π arredondado em duas casas decimais?', resposta: '3,14', dif: 30 },
    { pergunta: 'Quanto é 15% de 200?', resposta: '30', dif: 30 },
    { pergunta: 'Qual é a raiz quadrada de 144?', resposta: '12', dif: 12 },
    { pergunta: 'Quanto é 2¹⁰?', resposta: '1024', dif: 35 },
    { pergunta: 'Quantos lados tem um heptágono?', resposta: '7', dif: 30 },
    { pergunta: 'Qual é a soma dos ângulos internos de um triângulo?', resposta: '180°', aceita: ['180 graus'], dif: 15 },
    { pergunta: 'Qual é o próximo número da sequência 2, 4, 8, 16, ...?', resposta: '32', dif: 30 },
    { pergunta: 'Quanto é 1/4 em porcentagem?', resposta: '25%', aceita: ['25', 'um quarto'], dif: 30 },
    { pergunta: 'Quantos minutos há em 2,5 horas?', resposta: '150', dif: 30 },
    { pergunta: 'Quanto é 3³?', resposta: '27', dif: 15 },
    { pergunta: 'Quantos graus tem um ângulo reto?', resposta: '90°', aceita: ['90 graus'], dif: 12 },
    { pergunta: 'Qual é o único número primo que também é par?', resposta: '2', dif: 30 },
    { pergunta: 'Qual é a soma dos ângulos internos de um quadrilátero?', resposta: '360°', aceita: ['360 graus'], dif: 30 },
    { pergunta: 'Um produto custa R$ 80 com 25% de desconto. Qual o preço final?', resposta: 'R$ 60', aceita: ['60', '60 reais'], dif: 30 },
    { pergunta: 'Quanto é 0,5 + 0,25?', resposta: '0,75', dif: 30 },
    { pergunta: 'Quantos centímetros há em 1 metro?', resposta: '100', dif: 10 },
    { pergunta: 'Quanto é 144 ÷ 12?', resposta: '12', dif: 12 },
    { pergunta: 'Qual é o dobro de 47?', resposta: '94', dif: 15 },
    { pergunta: 'Quantas faces tem um cubo?', resposta: '6', dif: 12 },
    { pergunta: 'Quanto é 100 − 37?', resposta: '63', dif: 12 },
    { pergunta: 'Qual é o resultado de 25 × 4?', resposta: '100', dif: 10 }
  ],

  esportes: [
    { pergunta: 'Quantos jogadores de um time de futebol ficam em campo?', resposta: '11', dif: 12 },
    { pergunta: 'Quem é o maior artilheiro da história da Seleção Brasileira?', resposta: 'Neymar', dif: 40 },
    { pergunta: 'Quantas Copas do Mundo o Brasil já venceu?', resposta: '5', dif: 15 },
    { pergunta: 'Em qual esporte se usa o termo "home run"?', resposta: 'Beisebol', dif: 40 },
    { pergunta: 'Quantos jogadores de basquete ficam em quadra por time?', resposta: '5', dif: 15 },
    { pergunta: 'Qual país sediou a Copa do Mundo de 2014?', resposta: 'Brasil', dif: 15 },
    { pergunta: 'Quem é conhecido como "O Rei do Futebol"?', resposta: 'Pelé', dif: 12 },
    { pergunta: 'Em qual esporte Michael Jordan se destacou?', resposta: 'Basquete', dif: 12 },
    { pergunta: 'Qual torneio de tênis é disputado na grama, em Londres?', resposta: 'Wimbledon', dif: 40 },
    { pergunta: 'Qual piloto brasileiro foi tricampeão mundial de Fórmula 1?', resposta: 'Ayrton Senna', aceita: ['Senna'], dif: 40 },
    { pergunta: 'Quantos anéis formam o símbolo olímpico?', resposta: '5', dif: 15 },
    { pergunta: 'Qual esporte usa raquete e peteca (volante)?', resposta: 'Badminton', dif: 40 },
    { pergunta: 'Em qual país surgiu o judô?', resposta: 'Japão', dif: 20 },
    { pergunta: 'Qual clube tem mais títulos da Liga dos Campeões da UEFA?', resposta: 'Real Madrid', aceita: ['Real'], dif: 40 },
    { pergunta: 'Qual é a distância oficial de uma maratona?', resposta: '42,195 km', aceita: ['42195', '42 km', '42'], dif: 40 },
    { pergunta: 'Quem é conhecido pelo apelido "CR7"?', resposta: 'Cristiano Ronaldo', aceita: ['CR7', 'Cristiano'], dif: 40 },
    { pergunta: 'Qual seleção venceu a Copa do Mundo de 2022?', resposta: 'Argentina', dif: 25 },
    { pergunta: 'Em qual esporte se usa taco e buracos no campo?', resposta: 'Golfe', dif: 40 },
    { pergunta: 'Quantos tempos tem uma partida oficial de futebol?', resposta: '2', dif: 40 },
    { pergunta: 'De quantos em quantos anos acontecem os Jogos Olímpicos de Verão?', resposta: '4 anos', aceita: ['4', 'quatro'], dif: 40 },
    { pergunta: 'Quantos pontos vale um touchdown no futebol americano?', resposta: '6', dif: 12 },
    { pergunta: 'Qual seleção é a maior campeã mundial de vôlei masculino em Copas do Mundo?', resposta: 'Brasil', dif: 15 }
  ],

  anime: [
    { pergunta: 'Quem é o protagonista de One Piece?', resposta: 'Monkey D. Luffy', aceita: ['Luffy'], dif: 50 },
    { pergunta: 'Em qual anime aparece o personagem Eren Yeager?', resposta: 'Attack on Titan', aceita: ['Shingeki no Kyojin', 'Ataque dos Titãs'], dif: 50 },
    { pergunta: 'Qual é o nome do protagonista de Demon Slayer?', resposta: 'Tanjiro Kamado', aceita: ['Tanjiro'], dif: 50 },
    { pergunta: 'Qual estúdio produziu "A Viagem de Chihiro"?', resposta: 'Studio Ghibli', aceita: ['Ghibli'], dif: 50 },
    { pergunta: 'Qual é o nome do gato robô azul vindo do futuro?', resposta: 'Doraemon', dif: 25 },
    { pergunta: 'Em Naruto, qual é a vila natal do protagonista?', resposta: 'Konoha', aceita: ['Vila Oculta da Folha', 'Vila da Folha'], dif: 50 },
    { pergunta: 'Qual anime tem a alquimia como tema central?', resposta: 'Fullmetal Alchemist', aceita: ['FMA'], dif: 50 },
    { pergunta: 'Quem é o líder do Time 7 em Naruto?', resposta: 'Kakashi Hatake', aceita: ['Kakashi'], dif: 50 },
    { pergunta: 'Qual é o nome do irmão mais novo de Edward Elric?', resposta: 'Alphonse', dif: 50 },
    { pergunta: 'Qual Pokémon acompanha o Ash desde o primeiro episódio?', resposta: 'Pikachu', dif: 12 },
    { pergunta: 'Quem é o protagonista de Jujutsu Kaisen?', resposta: 'Yuji Itadori', aceita: ['Itadori', 'Yuji'], dif: 50 },
    { pergunta: 'Em Dragon Ball, quem é o príncipe dos saiyajins?', resposta: 'Vegeta', dif: 50 },
    { pergunta: 'Qual é o golpe mais famoso do Goku?', resposta: 'Kamehameha', dif: 20 },
    { pergunta: 'Quem é o protagonista de My Hero Academia?', resposta: 'Izuku Midoriya', aceita: ['Deku', 'Midoriya'], dif: 50 },
    { pergunta: 'Qual anime se passa dentro de um jogo online do qual não se pode sair?', resposta: 'Sword Art Online', aceita: ['SAO'], dif: 50 },
    { pergunta: 'Quem escreveu e desenhou o mangá One Piece?', resposta: 'Eiichiro Oda', aceita: ['Oda'], dif: 50 },
    { pergunta: 'Em Death Note, qual é o nome do shinigami que derruba o caderno?', resposta: 'Ryuk', dif: 50 },
    { pergunta: 'Qual é o protagonista de Bleach?', resposta: 'Ichigo Kurosaki', aceita: ['Ichigo'], dif: 50 },
    { pergunta: 'Qual anime tem o vôlei como tema principal?', resposta: 'Haikyuu!!', dif: 50 },
    { pergunta: 'Em Naruto, qual criatura está selada dentro do protagonista?', resposta: 'Kurama, a Raposa de Nove Caudas', aceita: ['Kurama', 'Kyuubi', 'Raposa de Nove Caudas'], dif: 50 },
    { pergunta: 'Quem é o professor mais forte da escola em Jujutsu Kaisen?', resposta: 'Satoru Gojo', aceita: ['Gojo'], dif: 50 },
    { pergunta: 'Qual anime acompanha Light Yagami e o detetive L?', resposta: 'Death Note', dif: 50 }
  ],

  musica: [
    { pergunta: 'Qual banda gravou "Bohemian Rhapsody"?', resposta: 'Queen', dif: 20 },
    { pergunta: 'Qual banda lançou a música "Let It Be"?', resposta: 'The Beatles', aceita: ['Beatles'], dif: 15 },
    { pergunta: 'Quem é conhecido como "O Rei do Pop"?', resposta: 'Michael Jackson', aceita: ['MJ'], dif: 15 },
    { pergunta: 'Qual artista lançou o álbum "1989"?', resposta: 'Taylor Swift', aceita: ['Swift'], dif: 40 },
    { pergunta: 'Qual dupla sertaneja eternizou a música "Evidências"?', resposta: 'Chitãozinho & Xororó', aceita: ['Chitãozinho e Xororó'], dif: 40 },
    { pergunta: 'Qual banda brasileira gravou "Tempo Perdido"?', resposta: 'Legião Urbana', dif: 40 },
    { pergunta: 'Quantas cordas tem um violão tradicional?', resposta: '6', dif: 12 },
    { pergunta: 'Quem compôs a música "Garota de Ipanema"?', resposta: 'Tom Jobim', aceita: ['Antônio Carlos Jobim', 'Jobim'], dif: 40 },
    { pergunta: 'Qual banda tem Mick Jagger como vocalista?', resposta: 'The Rolling Stones', aceita: ['Rolling Stones'], dif: 40 },
    { pergunta: 'Quem canta "Rolling in the Deep"?', resposta: 'Adele', dif: 40 },
    { pergunta: 'Quem canta "Shape of You"?', resposta: 'Ed Sheeran', aceita: ['Sheeran'], dif: 40 },
    { pergunta: 'Qual banda gravou "Stairway to Heaven"?', resposta: 'Led Zeppelin', aceita: ['Zeppelin'], dif: 40 },
    { pergunta: 'Quem é conhecida como "A Rainha do Pop"?', resposta: 'Madonna', dif: 40 },
    { pergunta: 'Qual gênero musical nasceu na Jamaica?', resposta: 'Reggae', dif: 40 },
    { pergunta: 'Qual banda gravou "Smells Like Teen Spirit"?', resposta: 'Nirvana', dif: 40 },
    { pergunta: 'Quem compôs a 9ª Sinfonia, que inclui a "Ode à Alegria"?', resposta: 'Beethoven', dif: 40 },
    { pergunta: 'Qual banda lançou o álbum "The Dark Side of the Moon"?', resposta: 'Pink Floyd', dif: 40 },
    { pergunta: 'Quem canta "Ai Se Eu Te Pego"?', resposta: 'Michel Teló', aceita: ['Teló'], dif: 40 },
    { pergunta: 'Quem é chamado de "Rei do Baião"?', resposta: 'Luiz Gonzaga', aceita: ['Gonzagão', 'Gonzaga'], dif: 40 },
    { pergunta: 'Qual artista lançou o álbum "Thriller"?', resposta: 'Michael Jackson', aceita: ['MJ'], dif: 15 },
    { pergunta: 'Quantas teclas tem um piano de cauda padrão?', resposta: '88', dif: 40 },
    { pergunta: 'Qual banda de rock brasileira teve Cazuza como vocalista?', resposta: 'Barão Vermelho', dif: 40 },
    ...LETRAS_MUSICA
  ],

  cinema: [
    { pergunta: 'Quem interpreta Jack Sparrow em "Piratas do Caribe"?', resposta: 'Johnny Depp', aceita: ['Depp'], dif: 15 },
    { pergunta: 'Quem dirigiu o filme "Titanic"?', resposta: 'James Cameron', aceita: ['Cameron'], dif: 40 },
    { pergunta: 'Quem interpreta Tony Stark, o Homem de Ferro?', resposta: 'Robert Downey Jr.', aceita: ['Robert Downey Junior', 'RDJ'], dif: 40 },
    { pergunta: 'De qual franquia é a frase "Que a Força esteja com você"?', resposta: 'Star Wars', aceita: ['Guerra nas Estrelas'], dif: 40 },
    { pergunta: 'Quem interpreta Harry Potter nos filmes?', resposta: 'Daniel Radcliffe', aceita: ['Radcliffe'], dif: 40 },
    { pergunta: 'Qual filme brasileiro retrata a vida em uma favela carioca e foi indicado ao Oscar?', resposta: 'Cidade de Deus', dif: 40 },
    { pergunta: 'Quem interpreta o Coringa no filme "Coringa" (2019)?', resposta: 'Joaquin Phoenix', aceita: ['Phoenix'], dif: 40 },
    { pergunta: 'Qual estúdio produziu "Toy Story"?', resposta: 'Pixar', dif: 20 },
    { pergunta: 'Quem interpreta Neo em "Matrix"?', resposta: 'Keanu Reeves', aceita: ['Keanu'], dif: 40 },
    { pergunta: 'Qual série tem Walter White e Jesse Pinkman como protagonistas?', resposta: 'Breaking Bad', dif: 40 },
    { pergunta: 'Quem dirigiu "Pulp Fiction"?', resposta: 'Quentin Tarantino', aceita: ['Tarantino'], dif: 40 },
    { pergunta: 'Em "O Senhor dos Anéis", quem leva o Um Anel até a Montanha da Perdição?', resposta: 'Frodo Bolseiro', aceita: ['Frodo'], dif: 40 },
    { pergunta: 'Quem interpreta Hermione Granger?', resposta: 'Emma Watson', aceita: ['Watson'], dif: 40 },
    { pergunta: 'Em qual cidade fictícia se passa "Stranger Things"?', resposta: 'Hawkins', dif: 40 },
    { pergunta: 'Quem interpretou Forrest Gump?', resposta: 'Tom Hanks', aceita: ['Hanks'], dif: 25 },
    { pergunta: 'Qual filme ganhou o Oscar de Melhor Filme em 2020?', resposta: 'Parasita', aceita: ['Parasite'], dif: 40 },
    { pergunta: 'Quem interpreta a Viúva Negra nos filmes da Marvel?', resposta: 'Scarlett Johansson', aceita: ['Scarlett'], dif: 40 },
    { pergunta: 'Qual animação tem Simba como protagonista?', resposta: 'O Rei Leão', aceita: ['Rei Leão', 'The Lion King'], dif: 40 },
    { pergunta: 'Quem dirigiu "Jurassic Park"?', resposta: 'Steven Spielberg', aceita: ['Spielberg'], dif: 40 },
    { pergunta: 'Qual série sul-coreana virou fenômeno com jogos infantis mortais?', resposta: 'Round 6', aceita: ['Squid Game'], dif: 40 },
    { pergunta: 'Quem interpreta Wolverine nos filmes dos X-Men?', resposta: 'Hugh Jackman', aceita: ['Jackman'], dif: 40 },
    { pergunta: 'De qual filme é a frase "Vou fazer uma oferta que ele não poderá recusar"?', resposta: 'O Poderoso Chefão', aceita: ['Poderoso Chefão', 'The Godfather'], dif: 40 }
  ],

  historia: [
    { pergunta: 'Em que ano os portugueses chegaram ao Brasil?', resposta: '1500', dif: 15 },
    { pergunta: 'Quem foi o primeiro presidente dos Estados Unidos?', resposta: 'George Washington', aceita: ['Washington'], dif: 45 },
    { pergunta: 'Em que ano terminou a Segunda Guerra Mundial?', resposta: '1945', dif: 20 },
    { pergunta: 'Quem pintou a Mona Lisa?', resposta: 'Leonardo da Vinci', aceita: ['Da Vinci', 'Leonardo'], dif: 15 },
    { pergunta: 'Qual civilização construiu as pirâmides de Gizé?', resposta: 'Egípcios', aceita: ['Egito', 'egípcios antigos'], dif: 45 },
    { pergunta: 'Em que ano caiu o Muro de Berlim?', resposta: '1989', dif: 45 },
    { pergunta: 'Quem proclamou a Independência do Brasil?', resposta: 'Dom Pedro I', aceita: ['Pedro I', 'Dom Pedro'], dif: 45 },
    { pergunta: 'Júlio César governou qual império?', resposta: 'Romano', dif: 45 },
    { pergunta: 'Em que ano o homem pisou na Lua pela primeira vez?', resposta: '1969', dif: 25 },
    { pergunta: 'Qual navegador português chegou às Índias pelo mar em 1498?', resposta: 'Vasco da Gama', aceita: ['Gama'], dif: 45 },
    { pergunta: 'Em que ano a escravidão foi abolida no Brasil?', resposta: '1888', dif: 45 },
    { pergunta: 'Quem escreveu a obra "O Príncipe"?', resposta: 'Maquiavel', aceita: ['Nicolau Maquiavel', 'Machiavelli'], dif: 45 },
    { pergunta: 'Qual foi a primeira capital do Brasil?', resposta: 'Salvador', dif: 45 },
    { pergunta: 'Quem liderou a Revolução Cubana?', resposta: 'Fidel Castro', aceita: ['Fidel'], dif: 45 },
    { pergunta: 'Em qual século ocorreu a Revolução Francesa?', resposta: 'Século XVIII', aceita: ['XVIII', '18'], dif: 45 },
    { pergunta: 'Quem chegou à América em 1492?', resposta: 'Cristóvão Colombo', aceita: ['Colombo'], dif: 45 },
    { pergunta: 'Qual país construiu a Grande Muralha?', resposta: 'China', dif: 25 },
    { pergunta: 'Quem foi a primeira mulher a ganhar um Prêmio Nobel?', resposta: 'Marie Curie', aceita: ['Curie', 'Madame Curie'], dif: 45 },
    { pergunta: 'Qual cidade foi soterrada pela erupção do Vesúvio em 79 d.C.?', resposta: 'Pompeia', dif: 45 },
    { pergunta: 'Em que ano começou a Primeira Guerra Mundial?', resposta: '1914', dif: 45 },
    { pergunta: 'Quem liderou o movimento pacífico pela independência da Índia?', resposta: 'Mahatma Gandhi', aceita: ['Gandhi'], dif: 45 },
    { pergunta: 'Qual imperador francês foi derrotado na Batalha de Waterloo?', resposta: 'Napoleão Bonaparte', aceita: ['Napoleão'], dif: 45 }
  ],

  ciencia: [
    { pergunta: 'Qual é a fórmula química da água?', resposta: 'H2O', aceita: ['água', 'H2O'], dif: 10 },
    { pergunta: 'Qual é o planeta mais próximo do Sol?', resposta: 'Mercúrio', dif: 40 },
    { pergunta: 'Quantos ossos tem o corpo humano adulto?', resposta: '206', dif: 40 },
    { pergunta: 'Qual gás as plantas absorvem durante a fotossíntese?', resposta: 'Gás carbônico', aceita: ['CO2', 'dióxido de carbono', 'gás carbônico'], dif: 40 },
    { pergunta: 'Quem formulou a Teoria da Relatividade?', resposta: 'Albert Einstein', aceita: ['Einstein'], dif: 40 },
    { pergunta: 'Qual é o maior planeta do Sistema Solar?', resposta: 'Júpiter', dif: 15 },
    { pergunta: 'Qual órgão é responsável por bombear o sangue?', resposta: 'Coração', dif: 10 },
    { pergunta: 'Qual é o símbolo químico do ouro?', resposta: 'Au', dif: 45 },
    { pergunta: 'Quantos cromossomos tem uma célula humana normal?', resposta: '46', dif: 40 },
    { pergunta: 'Qual planeta é conhecido como "Planeta Vermelho"?', resposta: 'Marte', dif: 12 },
    { pergunta: 'Quem propôs a teoria da evolução por seleção natural?', resposta: 'Charles Darwin', aceita: ['Darwin'], dif: 40 },
    { pergunta: 'Qual é o osso mais longo do corpo humano?', resposta: 'Fêmur', dif: 40 },
    { pergunta: 'Qual é a fórmula química do sal de cozinha?', resposta: 'NaCl', aceita: ['cloreto de sódio'], dif: 40 },
    { pergunta: 'Qual é o maior animal do mundo?', resposta: 'Baleia-azul', aceita: ['baleia azul'], dif: 40 },
    { pergunta: 'Qual parte da célula guarda o material genético?', resposta: 'Núcleo', dif: 40 },
    { pergunta: 'Qual cientista descobriu a penicilina?', resposta: 'Alexander Fleming', aceita: ['Fleming'], dif: 40 },
    { pergunta: 'Qual metal é líquido em temperatura ambiente?', resposta: 'Mercúrio', dif: 40 },
    { pergunta: 'Quantos planetas existem no Sistema Solar?', resposta: '8', dif: 40 },
    { pergunta: 'Qual é a unidade de medida de força no Sistema Internacional?', resposta: 'Newton', dif: 40 },
    { pergunta: 'Qual é a velocidade aproximada da luz no vácuo?', resposta: '300.000 km/s', aceita: ['300000', '300 mil km/s', '300000 km/s'], dif: 40 },
    { pergunta: 'Qual é o gás mais abundante na atmosfera da Terra?', resposta: 'Nitrogênio', dif: 40 },
    { pergunta: 'Qual é o menor osso do corpo humano?', resposta: 'Estribo', dif: 70 }
  ],

  games: [
    { pergunta: 'Qual é o encanador mais famoso dos videogames?', resposta: 'Mario', aceita: ['Super Mario'], dif: 10 },
    { pergunta: 'Em Minecraft, qual criatura explode ao se aproximar do jogador?', resposta: 'Creeper', dif: 45 },
    { pergunta: 'Qual empresa criou o PlayStation?', resposta: 'Sony', dif: 15 },
    { pergunta: 'Qual é o nome do ouriço azul mascote da SEGA?', resposta: 'Sonic', dif: 15 },
    { pergunta: 'Quem é o protagonista da série The Legend of Zelda?', resposta: 'Link', dif: 45 },
    { pergunta: 'Qual empresa desenvolveu Fortnite?', resposta: 'Epic Games', aceita: ['Epic'], dif: 45 },
    { pergunta: 'Qual é o principal vilão da série Super Mario?', resposta: 'Bowser', dif: 45 },
    { pergunta: 'Qual é a cidade fictícia onde se passa GTA V?', resposta: 'Los Santos', aceita: ['Los Santos, San Andreas'], dif: 45 },
    { pergunta: 'Qual console a Nintendo lançou em 2017?', resposta: 'Nintendo Switch', aceita: ['Switch'], dif: 45 },
    { pergunta: 'Quem é a protagonista da série Tomb Raider?', resposta: 'Lara Croft', aceita: ['Lara'], dif: 45 },
    { pergunta: 'Em qual série de jogos Kratos é o protagonista?', resposta: 'God of War', dif: 45 },
    { pergunta: 'Qual empresa desenvolveu Counter-Strike?', resposta: 'Valve', dif: 45 },
    { pergunta: 'Qual é a primeira região do mundo Pokémon?', resposta: 'Kanto', dif: 45 },
    { pergunta: 'Quantos jogadores tem cada time em uma partida de League of Legends?', resposta: '5', dif: 15 },
    { pergunta: 'Qual é o jogo mais vendido de todos os tempos?', resposta: 'Minecraft', dif: 15 },
    { pergunta: 'Qual empresa criou o Xbox?', resposta: 'Microsoft', dif: 20 },
    { pergunta: 'Em qual jogo você cuida de uma fazenda herdada do avô?', resposta: 'Stardew Valley', dif: 55 },
    { pergunta: 'Qual jogo de terror tem o personagem Leon S. Kennedy?', resposta: 'Resident Evil', dif: 45 },
    { pergunta: 'Qual empresa desenvolveu The Witcher 3?', resposta: 'CD Projekt Red', aceita: ['CD Projekt'], dif: 70 },
    { pergunta: 'Qual série de jogos ficou famosa pela dificuldade e pela frase "Git Gud"?', resposta: 'Dark Souls', dif: 45 },
    { pergunta: 'Qual jogo de cartas colecionáveis digital é da Blizzard?', resposta: 'Hearthstone', dif: 60 },
    { pergunta: 'Qual estúdio criou a série Assassin\'s Creed?', resposta: 'Ubisoft', dif: 45 }
  ]
};

module.exports = { CATEGORIAS, QUESTOES };
